// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cds.proto

package discoveryservice

import (
	v2 "envoy/api/v2"
	auth "envoy/api/v2/auth"
	cluster "envoy/api/v2/cluster"
	core "envoy/api/v2/core"
	_type "envoy/type"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Refer to :ref:`service discovery type <arch_overview_service_discovery_types>`
// for an explanation on each type.
type Cluster_DiscoveryType int32

const (
	// Refer to the :ref:`static discovery type<arch_overview_service_discovery_types_static>`
	// for an explanation.
	Cluster_STATIC Cluster_DiscoveryType = 0
	// Refer to the :ref:`strict DNS discovery
	// type<arch_overview_service_discovery_types_strict_dns>`
	// for an explanation.
	Cluster_STRICT_DNS Cluster_DiscoveryType = 1
	// Refer to the :ref:`logical DNS discovery
	// type<arch_overview_service_discovery_types_logical_dns>`
	// for an explanation.
	Cluster_LOGICAL_DNS Cluster_DiscoveryType = 2
	// Refer to the :ref:`service discovery type<arch_overview_service_discovery_types_eds>`
	// for an explanation.
	Cluster_EDS Cluster_DiscoveryType = 3
	// Refer to the :ref:`original destination discovery
	// type<arch_overview_service_discovery_types_original_destination>`
	// for an explanation.
	Cluster_ORIGINAL_DST Cluster_DiscoveryType = 4
)

var Cluster_DiscoveryType_name = map[int32]string{
	0: "STATIC",
	1: "STRICT_DNS",
	2: "LOGICAL_DNS",
	3: "EDS",
	4: "ORIGINAL_DST",
}

var Cluster_DiscoveryType_value = map[string]int32{
	"STATIC":       0,
	"STRICT_DNS":   1,
	"LOGICAL_DNS":  2,
	"EDS":          3,
	"ORIGINAL_DST": 4,
}

func (x Cluster_DiscoveryType) String() string {
	return proto.EnumName(Cluster_DiscoveryType_name, int32(x))
}

func (Cluster_DiscoveryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 0}
}

// Refer to :ref:`load balancer type <arch_overview_load_balancing_types>` architecture
// overview section for information on each type.
type Cluster_LbPolicy int32

const (
	// Refer to the :ref:`round robin load balancing
	// policy<arch_overview_load_balancing_types_round_robin>`
	// for an explanation.
	Cluster_ROUND_ROBIN Cluster_LbPolicy = 0
	// Refer to the :ref:`least request load balancing
	// policy<arch_overview_load_balancing_types_least_request>`
	// for an explanation.
	Cluster_LEAST_REQUEST Cluster_LbPolicy = 1
	// Refer to the :ref:`ring hash load balancing
	// policy<arch_overview_load_balancing_types_ring_hash>`
	// for an explanation.
	Cluster_RING_HASH Cluster_LbPolicy = 2
	// Refer to the :ref:`random load balancing
	// policy<arch_overview_load_balancing_types_random>`
	// for an explanation.
	Cluster_RANDOM Cluster_LbPolicy = 3
	// Refer to the :ref:`original destination load balancing
	// policy<arch_overview_load_balancing_types_original_destination>`
	// for an explanation.
	Cluster_ORIGINAL_DST_LB Cluster_LbPolicy = 4
	// Refer to the :ref:`Maglev load balancing policy<arch_overview_load_balancing_types_maglev>`
	// for an explanation.
	Cluster_MAGLEV Cluster_LbPolicy = 5
)

var Cluster_LbPolicy_name = map[int32]string{
	0: "ROUND_ROBIN",
	1: "LEAST_REQUEST",
	2: "RING_HASH",
	3: "RANDOM",
	4: "ORIGINAL_DST_LB",
	5: "MAGLEV",
}

var Cluster_LbPolicy_value = map[string]int32{
	"ROUND_ROBIN":     0,
	"LEAST_REQUEST":   1,
	"RING_HASH":       2,
	"RANDOM":          3,
	"ORIGINAL_DST_LB": 4,
	"MAGLEV":          5,
}

func (x Cluster_LbPolicy) String() string {
	return proto.EnumName(Cluster_LbPolicy_name, int32(x))
}

func (Cluster_LbPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 1}
}

// When V4_ONLY is selected, the DNS resolver will only perform a lookup for
// addresses in the IPv4 family. If V6_ONLY is selected, the DNS resolver will
// only perform a lookup for addresses in the IPv6 family. If AUTO is
// specified, the DNS resolver will first perform a lookup for addresses in
// the IPv6 family and fallback to a lookup for addresses in the IPv4 family.
// For cluster types other than
// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>` and
// :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
// this setting is
// ignored.
type Cluster_DnsLookupFamily int32

const (
	Cluster_AUTO    Cluster_DnsLookupFamily = 0
	Cluster_V4_ONLY Cluster_DnsLookupFamily = 1
	Cluster_V6_ONLY Cluster_DnsLookupFamily = 2
)

var Cluster_DnsLookupFamily_name = map[int32]string{
	0: "AUTO",
	1: "V4_ONLY",
	2: "V6_ONLY",
}

var Cluster_DnsLookupFamily_value = map[string]int32{
	"AUTO":    0,
	"V4_ONLY": 1,
	"V6_ONLY": 2,
}

func (x Cluster_DnsLookupFamily) String() string {
	return proto.EnumName(Cluster_DnsLookupFamily_name, int32(x))
}

func (Cluster_DnsLookupFamily) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 2}
}

type Cluster_ClusterProtocolSelection int32

const (
	// Cluster can only operate on one of the possible upstream protocols (HTTP1.1, HTTP2).
	// If :ref:`http2_protocol_options <envoy_api_field_Cluster.http2_protocol_options>` are
	// present, HTTP2 will be used, otherwise HTTP1.1 will be used.
	Cluster_USE_CONFIGURED_PROTOCOL Cluster_ClusterProtocolSelection = 0
	// Use HTTP1.1 or HTTP2, depending on which one is used on the downstream connection.
	Cluster_USE_DOWNSTREAM_PROTOCOL Cluster_ClusterProtocolSelection = 1
)

var Cluster_ClusterProtocolSelection_name = map[int32]string{
	0: "USE_CONFIGURED_PROTOCOL",
	1: "USE_DOWNSTREAM_PROTOCOL",
}

var Cluster_ClusterProtocolSelection_value = map[string]int32{
	"USE_CONFIGURED_PROTOCOL": 0,
	"USE_DOWNSTREAM_PROTOCOL": 1,
}

func (x Cluster_ClusterProtocolSelection) String() string {
	return proto.EnumName(Cluster_ClusterProtocolSelection_name, int32(x))
}

func (Cluster_ClusterProtocolSelection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 3}
}

// If NO_FALLBACK is selected, a result
// equivalent to no healthy hosts is reported. If ANY_ENDPOINT is selected,
// any cluster endpoint may be returned (subject to policy, health checks,
// etc). If DEFAULT_SUBSET is selected, load balancing is performed over the
// endpoints matching the values from the default_subset field.
type Cluster_LbSubsetConfig_LbSubsetFallbackPolicy int32

const (
	Cluster_LbSubsetConfig_NO_FALLBACK    Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 0
	Cluster_LbSubsetConfig_ANY_ENDPOINT   Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 1
	Cluster_LbSubsetConfig_DEFAULT_SUBSET Cluster_LbSubsetConfig_LbSubsetFallbackPolicy = 2
)

var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name = map[int32]string{
	0: "NO_FALLBACK",
	1: "ANY_ENDPOINT",
	2: "DEFAULT_SUBSET",
}

var Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value = map[string]int32{
	"NO_FALLBACK":    0,
	"ANY_ENDPOINT":   1,
	"DEFAULT_SUBSET": 2,
}

func (x Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) String() string {
	return proto.EnumName(Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, int32(x))
}

func (Cluster_LbSubsetConfig_LbSubsetFallbackPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 3, 0}
}

// The hash function used to hash hosts onto the ketama ring.
type Cluster_RingHashLbConfig_HashFunction int32

const (
	// Use `xxHash <https://github.com/Cyan4973/xxHash>`_, this is the default hash function.
	Cluster_RingHashLbConfig_XX_HASH Cluster_RingHashLbConfig_HashFunction = 0
	// Use `MurmurHash2 <https://sites.google.com/site/murmurhash/>`_, this is compatible with
	// std:hash<string> in GNU libstdc++ 3.4.20 or above. This is typically the case when compiled
	// on Linux and not macOS.
	Cluster_RingHashLbConfig_MURMUR_HASH_2 Cluster_RingHashLbConfig_HashFunction = 1
)

var Cluster_RingHashLbConfig_HashFunction_name = map[int32]string{
	0: "XX_HASH",
	1: "MURMUR_HASH_2",
}

var Cluster_RingHashLbConfig_HashFunction_value = map[string]int32{
	"XX_HASH":       0,
	"MURMUR_HASH_2": 1,
}

func (x Cluster_RingHashLbConfig_HashFunction) String() string {
	return proto.EnumName(Cluster_RingHashLbConfig_HashFunction_name, int32(x))
}

func (Cluster_RingHashLbConfig_HashFunction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 5, 0}
}

// Configuration for a single upstream cluster.
// [#comment:next free field: 38]
type Cluster struct {
	// Supplies the name of the cluster which must be unique across all clusters.
	// The cluster name is used when emitting
	// :ref:`statistics <config_cluster_manager_cluster_stats>` if :ref:`alt_stat_name
	// <envoy_api_field_Cluster.alt_stat_name>` is not provided.
	// Any ``:`` in the cluster name will be converted to ``_`` when emitting statistics.
	// By default, the maximum length of a cluster name is limited to 60
	// characters. This limit can be increased by setting the
	// :option:`--max-obj-name-len` command line argument to the desired value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// An optional alternative to the cluster name to be used while emitting stats.
	// Any ``:`` in the name will be converted to ``_`` when emitting statistics. This should not be
	// confused with :ref:`Router Filter Header
	// <config_http_filters_router_x-envoy-upstream-alt-stat-name>`.
	AltStatName string `protobuf:"bytes,28,opt,name=alt_stat_name,json=altStatName,proto3" json:"alt_stat_name,omitempty"`
	// The :ref:`service discovery type <arch_overview_service_discovery_types>`
	// to use for resolving the cluster.
	Type Cluster_DiscoveryType `protobuf:"varint,2,opt,name=type,proto3,enum=envoy.api.v2.Cluster_DiscoveryType" json:"type,omitempty"`
	// Configuration to use for EDS updates for the Cluster.
	EdsClusterConfig *Cluster_EdsClusterConfig `protobuf:"bytes,3,opt,name=eds_cluster_config,json=edsClusterConfig,proto3" json:"eds_cluster_config,omitempty"`
	// The timeout for new network connections to hosts in the cluster.
	ConnectTimeout *duration.Duration `protobuf:"bytes,4,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	// Soft limit on size of the cluster’s connections read and write buffers. If
	// unspecified, an implementation defined default is applied (1MiB).
	PerConnectionBufferLimitBytes *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes,proto3" json:"per_connection_buffer_limit_bytes,omitempty"`
	// The :ref:`load balancer type <arch_overview_load_balancing_types>` to use
	// when picking a host in the cluster.
	LbPolicy Cluster_LbPolicy `protobuf:"varint,6,opt,name=lb_policy,json=lbPolicy,proto3,enum=envoy.api.v2.Cluster_LbPolicy" json:"lb_policy,omitempty"`
	// If the service discovery type is
	// :ref:`STATIC<envoy_api_enum_value_Cluster.DiscoveryType.STATIC>`,
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// then hosts is required.
	//
	// .. attention::
	//
	//   **This field is deprecated**. Set the
	//   :ref:`load_assignment<envoy_api_field_Cluster.load_assignment>` field instead.
	//
	Hosts []*core.Address `protobuf:"bytes,7,rep,name=hosts,proto3" json:"hosts,omitempty"` // Deprecated: Do not use.
	// Setting this is required for specifying members of
	// :ref:`STATIC<envoy_api_enum_value_Cluster.DiscoveryType.STATIC>`,
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>` clusters.
	// This field supersedes :ref:`hosts<envoy_api_field_Cluster.hosts>` field.
	// [#comment:TODO(dio): Deprecate the hosts field and add it to DEPRECATED.md
	// once load_assignment is implemented.]
	//
	// .. attention::
	//
	//   Setting this allows non-EDS cluster types to contain embedded EDS equivalent
	//   :ref:`endpoint assignments<envoy_api_msg_ClusterLoadAssignment>`.
	//   Setting this overrides :ref:`hosts<envoy_api_field_Cluster.hosts>` values.
	//
	LoadAssignment *v2.ClusterLoadAssignment `protobuf:"bytes,33,opt,name=load_assignment,json=loadAssignment,proto3" json:"load_assignment,omitempty"`
	// Optional :ref:`active health checking <arch_overview_health_checking>`
	// configuration for the cluster. If no
	// configuration is specified no health checking will be done and all cluster
	// members will be considered healthy at all times.
	HealthChecks []*core.HealthCheck `protobuf:"bytes,8,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	// Optional maximum requests for a single upstream connection. This parameter
	// is respected by both the HTTP/1.1 and HTTP/2 connection pool
	// implementations. If not specified, there is no limit. Setting this
	// parameter to 1 will effectively disable keep alive.
	MaxRequestsPerConnection *wrappers.UInt32Value `protobuf:"bytes,9,opt,name=max_requests_per_connection,json=maxRequestsPerConnection,proto3" json:"max_requests_per_connection,omitempty"`
	// Optional :ref:`circuit breaking <arch_overview_circuit_break>` for the cluster.
	CircuitBreakers *cluster.CircuitBreakers `protobuf:"bytes,10,opt,name=circuit_breakers,json=circuitBreakers,proto3" json:"circuit_breakers,omitempty"`
	// The TLS configuration for connections to the upstream cluster. If no TLS
	// configuration is specified, TLS will not be used for new connections.
	//
	// .. attention::
	//
	//   Server certificate verification is not enabled by default. Configure
	//   :ref:`trusted_ca<envoy_api_field_auth.CertificateValidationContext.trusted_ca>` to enable
	//   verification.
	TlsContext *auth.UpstreamTlsContext `protobuf:"bytes,11,opt,name=tls_context,json=tlsContext,proto3" json:"tls_context,omitempty"`
	// Additional options when handling HTTP requests. These options will be applicable to both
	// HTTP1 and HTTP2 requests.
	CommonHttpProtocolOptions *core.HttpProtocolOptions `protobuf:"bytes,29,opt,name=common_http_protocol_options,json=commonHttpProtocolOptions,proto3" json:"common_http_protocol_options,omitempty"`
	// Additional options when handling HTTP1 requests.
	HttpProtocolOptions *core.Http1ProtocolOptions `protobuf:"bytes,13,opt,name=http_protocol_options,json=httpProtocolOptions,proto3" json:"http_protocol_options,omitempty"`
	// Even if default HTTP2 protocol options are desired, this field must be
	// set so that Envoy will assume that the upstream supports HTTP/2 when
	// making new HTTP connection pool connections. Currently, Envoy only
	// supports prior knowledge for upstream connections. Even if TLS is used
	// with ALPN, `http2_protocol_options` must be specified. As an aside this allows HTTP/2
	// connections to happen over plain text.
	Http2ProtocolOptions *core.Http2ProtocolOptions `protobuf:"bytes,14,opt,name=http2_protocol_options,json=http2ProtocolOptions,proto3" json:"http2_protocol_options,omitempty"`
	// The extension_protocol_options field is used to provide extension-specific protocol options
	// for upstream connections. The key should match the extension filter name, such as
	// "envoy.filters.network.thrift_proxy". See the extension's documentation for details on
	// specific options.
	ExtensionProtocolOptions map[string]*_struct.Struct `protobuf:"bytes,35,rep,name=extension_protocol_options,json=extensionProtocolOptions,proto3" json:"extension_protocol_options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Deprecated: Do not use.
	// The extension_protocol_options field is used to provide extension-specific protocol options
	// for upstream connections. The key should match the extension filter name, such as
	// "envoy.filters.network.thrift_proxy". See the extension's documentation for details on
	// specific options.
	TypedExtensionProtocolOptions map[string]*any.Any `protobuf:"bytes,36,rep,name=typed_extension_protocol_options,json=typedExtensionProtocolOptions,proto3" json:"typed_extension_protocol_options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If the DNS refresh rate is specified and the cluster type is either
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`,
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// this value is used as the cluster’s DNS refresh
	// rate. If this setting is not specified, the value defaults to 5000ms. For
	// cluster types other than
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// and :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`
	// this setting is ignored.
	DnsRefreshRate *duration.Duration `protobuf:"bytes,16,opt,name=dns_refresh_rate,json=dnsRefreshRate,proto3" json:"dns_refresh_rate,omitempty"`
	// The DNS IP address resolution policy. If this setting is not specified, the
	// value defaults to
	// :ref:`AUTO<envoy_api_enum_value_Cluster.DnsLookupFamily.AUTO>`.
	DnsLookupFamily Cluster_DnsLookupFamily `protobuf:"varint,17,opt,name=dns_lookup_family,json=dnsLookupFamily,proto3,enum=envoy.api.v2.Cluster_DnsLookupFamily" json:"dns_lookup_family,omitempty"`
	// If DNS resolvers are specified and the cluster type is either
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`,
	// or :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`,
	// this value is used to specify the cluster’s dns resolvers.
	// If this setting is not specified, the value defaults to the default
	// resolver, which uses /etc/resolv.conf for configuration. For cluster types
	// other than
	// :ref:`STRICT_DNS<envoy_api_enum_value_Cluster.DiscoveryType.STRICT_DNS>`
	// and :ref:`LOGICAL_DNS<envoy_api_enum_value_Cluster.DiscoveryType.LOGICAL_DNS>`
	// this setting is ignored.
	DnsResolvers []*core.Address `protobuf:"bytes,18,rep,name=dns_resolvers,json=dnsResolvers,proto3" json:"dns_resolvers,omitempty"`
	// If specified, outlier detection will be enabled for this upstream cluster.
	// Each of the configuration values can be overridden via
	// :ref:`runtime values <config_cluster_manager_cluster_runtime_outlier_detection>`.
	OutlierDetection *cluster.OutlierDetection `protobuf:"bytes,19,opt,name=outlier_detection,json=outlierDetection,proto3" json:"outlier_detection,omitempty"`
	// The interval for removing stale hosts from a cluster type
	// :ref:`ORIGINAL_DST<envoy_api_enum_value_Cluster.DiscoveryType.ORIGINAL_DST>`.
	// Hosts are considered stale if they have not been used
	// as upstream destinations during this interval. New hosts are added
	// to original destination clusters on demand as new connections are
	// redirected to Envoy, causing the number of hosts in the cluster to
	// grow over time. Hosts that are not stale (they are actively used as
	// destinations) are kept in the cluster, which allows connections to
	// them remain open, saving the latency that would otherwise be spent
	// on opening new connections. If this setting is not specified, the
	// value defaults to 5000ms. For cluster types other than
	// :ref:`ORIGINAL_DST<envoy_api_enum_value_Cluster.DiscoveryType.ORIGINAL_DST>`
	// this setting is ignored.
	CleanupInterval *duration.Duration `protobuf:"bytes,20,opt,name=cleanup_interval,json=cleanupInterval,proto3" json:"cleanup_interval,omitempty"`
	// Optional configuration used to bind newly established upstream connections.
	// This overrides any bind_config specified in the bootstrap proto.
	// If the address and port are empty, no bind will be performed.
	UpstreamBindConfig *core.BindConfig `protobuf:"bytes,21,opt,name=upstream_bind_config,json=upstreamBindConfig,proto3" json:"upstream_bind_config,omitempty"`
	// Configuration for load balancing subsetting.
	LbSubsetConfig *Cluster_LbSubsetConfig `protobuf:"bytes,22,opt,name=lb_subset_config,json=lbSubsetConfig,proto3" json:"lb_subset_config,omitempty"`
	// Optional configuration for the load balancing algorithm selected by
	// LbPolicy. Currently only
	// :ref:`RING_HASH<envoy_api_enum_value_Cluster.LbPolicy.RING_HASH>` and
	// :ref:`LEAST_REQUEST<envoy_api_enum_value_Cluster.LbPolicy.LEAST_REQUEST>`
	// has additional configuration options.
	// Specifying ring_hash_lb_config or least_request_lb_config without setting the corresponding
	// LbPolicy will generate an error at runtime.
	//
	// Types that are valid to be assigned to LbConfig:
	//	*Cluster_RingHashLbConfig_
	//	*Cluster_OriginalDstLbConfig_
	//	*Cluster_LeastRequestLbConfig_
	LbConfig isCluster_LbConfig `protobuf_oneof:"lb_config"`
	// Common configuration for all load balancer implementations.
	CommonLbConfig *Cluster_CommonLbConfig `protobuf:"bytes,27,opt,name=common_lb_config,json=commonLbConfig,proto3" json:"common_lb_config,omitempty"`
	// Optional custom transport socket implementation to use for upstream connections.
	TransportSocket *core.TransportSocket `protobuf:"bytes,24,opt,name=transport_socket,json=transportSocket,proto3" json:"transport_socket,omitempty"`
	// The Metadata field can be used to provide additional information about the
	// cluster. It can be used for stats, logging, and varying filter behavior.
	// Fields should use reverse DNS notation to denote which entity within Envoy
	// will need the information. For instance, if the metadata is intended for
	// the Router filter, the filter name should be specified as *envoy.router*.
	Metadata *core.Metadata `protobuf:"bytes,25,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Determines how Envoy selects the protocol used to speak to upstream hosts.
	ProtocolSelection Cluster_ClusterProtocolSelection `protobuf:"varint,26,opt,name=protocol_selection,json=protocolSelection,proto3,enum=envoy.api.v2.Cluster_ClusterProtocolSelection" json:"protocol_selection,omitempty"`
	// Optional options for upstream connections.
	UpstreamConnectionOptions *UpstreamConnectionOptions `protobuf:"bytes,30,opt,name=upstream_connection_options,json=upstreamConnectionOptions,proto3" json:"upstream_connection_options,omitempty"`
	// If an upstream host becomes unhealthy (as determined by the configured health checks
	// or outlier detection), immediately close all connections to the failed host.
	//
	// .. note::
	//
	//   This is currently only supported for connections created by tcp_proxy.
	//
	// .. note::
	//
	//   The current implementation of this feature closes all connections immediately when
	//   the unhealthy status is detected. If there are a large number of connections open
	//   to an upstream host that becomes unhealthy, Envoy may spend a substantial amount of
	//   time exclusively closing these connections, and not processing any other traffic.
	CloseConnectionsOnHostHealthFailure bool `protobuf:"varint,31,opt,name=close_connections_on_host_health_failure,json=closeConnectionsOnHostHealthFailure,proto3" json:"close_connections_on_host_health_failure,omitempty"`
	// If this cluster uses EDS or STRICT_DNS to configure its hosts, immediately drain
	// connections from any hosts that are removed from service discovery.
	//
	// This only affects behavior for hosts that are being actively health checked.
	// If this flag is not set to true, Envoy will wait until the hosts fail active health
	// checking before removing it from the cluster.
	DrainConnectionsOnHostRemoval bool     `protobuf:"varint,32,opt,name=drain_connections_on_host_removal,json=drainConnectionsOnHostRemoval,proto3" json:"drain_connections_on_host_removal,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetAltStatName() string {
	if m != nil {
		return m.AltStatName
	}
	return ""
}

func (m *Cluster) GetType() Cluster_DiscoveryType {
	if m != nil {
		return m.Type
	}
	return Cluster_STATIC
}

func (m *Cluster) GetEdsClusterConfig() *Cluster_EdsClusterConfig {
	if m != nil {
		return m.EdsClusterConfig
	}
	return nil
}

func (m *Cluster) GetConnectTimeout() *duration.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *Cluster) GetPerConnectionBufferLimitBytes() *wrappers.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

func (m *Cluster) GetLbPolicy() Cluster_LbPolicy {
	if m != nil {
		return m.LbPolicy
	}
	return Cluster_ROUND_ROBIN
}

// Deprecated: Do not use.
func (m *Cluster) GetHosts() []*core.Address {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Cluster) GetLoadAssignment() *v2.ClusterLoadAssignment {
	if m != nil {
		return m.LoadAssignment
	}
	return nil
}

func (m *Cluster) GetHealthChecks() []*core.HealthCheck {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *Cluster) GetMaxRequestsPerConnection() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return nil
}

func (m *Cluster) GetCircuitBreakers() *cluster.CircuitBreakers {
	if m != nil {
		return m.CircuitBreakers
	}
	return nil
}

func (m *Cluster) GetTlsContext() *auth.UpstreamTlsContext {
	if m != nil {
		return m.TlsContext
	}
	return nil
}

func (m *Cluster) GetCommonHttpProtocolOptions() *core.HttpProtocolOptions {
	if m != nil {
		return m.CommonHttpProtocolOptions
	}
	return nil
}

func (m *Cluster) GetHttpProtocolOptions() *core.Http1ProtocolOptions {
	if m != nil {
		return m.HttpProtocolOptions
	}
	return nil
}

func (m *Cluster) GetHttp2ProtocolOptions() *core.Http2ProtocolOptions {
	if m != nil {
		return m.Http2ProtocolOptions
	}
	return nil
}

// Deprecated: Do not use.
func (m *Cluster) GetExtensionProtocolOptions() map[string]*_struct.Struct {
	if m != nil {
		return m.ExtensionProtocolOptions
	}
	return nil
}

func (m *Cluster) GetTypedExtensionProtocolOptions() map[string]*any.Any {
	if m != nil {
		return m.TypedExtensionProtocolOptions
	}
	return nil
}

func (m *Cluster) GetDnsRefreshRate() *duration.Duration {
	if m != nil {
		return m.DnsRefreshRate
	}
	return nil
}

func (m *Cluster) GetDnsLookupFamily() Cluster_DnsLookupFamily {
	if m != nil {
		return m.DnsLookupFamily
	}
	return Cluster_AUTO
}

func (m *Cluster) GetDnsResolvers() []*core.Address {
	if m != nil {
		return m.DnsResolvers
	}
	return nil
}

func (m *Cluster) GetOutlierDetection() *cluster.OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *Cluster) GetCleanupInterval() *duration.Duration {
	if m != nil {
		return m.CleanupInterval
	}
	return nil
}

func (m *Cluster) GetUpstreamBindConfig() *core.BindConfig {
	if m != nil {
		return m.UpstreamBindConfig
	}
	return nil
}

func (m *Cluster) GetLbSubsetConfig() *Cluster_LbSubsetConfig {
	if m != nil {
		return m.LbSubsetConfig
	}
	return nil
}

type isCluster_LbConfig interface {
	isCluster_LbConfig()
}

type Cluster_RingHashLbConfig_ struct {
	RingHashLbConfig *Cluster_RingHashLbConfig `protobuf:"bytes,23,opt,name=ring_hash_lb_config,json=ringHashLbConfig,proto3,oneof"`
}

type Cluster_OriginalDstLbConfig_ struct {
	OriginalDstLbConfig *Cluster_OriginalDstLbConfig `protobuf:"bytes,34,opt,name=original_dst_lb_config,json=originalDstLbConfig,proto3,oneof"`
}

type Cluster_LeastRequestLbConfig_ struct {
	LeastRequestLbConfig *Cluster_LeastRequestLbConfig `protobuf:"bytes,37,opt,name=least_request_lb_config,json=leastRequestLbConfig,proto3,oneof"`
}

func (*Cluster_RingHashLbConfig_) isCluster_LbConfig() {}

func (*Cluster_OriginalDstLbConfig_) isCluster_LbConfig() {}

func (*Cluster_LeastRequestLbConfig_) isCluster_LbConfig() {}

func (m *Cluster) GetLbConfig() isCluster_LbConfig {
	if m != nil {
		return m.LbConfig
	}
	return nil
}

func (m *Cluster) GetRingHashLbConfig() *Cluster_RingHashLbConfig {
	if x, ok := m.GetLbConfig().(*Cluster_RingHashLbConfig_); ok {
		return x.RingHashLbConfig
	}
	return nil
}

func (m *Cluster) GetOriginalDstLbConfig() *Cluster_OriginalDstLbConfig {
	if x, ok := m.GetLbConfig().(*Cluster_OriginalDstLbConfig_); ok {
		return x.OriginalDstLbConfig
	}
	return nil
}

func (m *Cluster) GetLeastRequestLbConfig() *Cluster_LeastRequestLbConfig {
	if x, ok := m.GetLbConfig().(*Cluster_LeastRequestLbConfig_); ok {
		return x.LeastRequestLbConfig
	}
	return nil
}

func (m *Cluster) GetCommonLbConfig() *Cluster_CommonLbConfig {
	if m != nil {
		return m.CommonLbConfig
	}
	return nil
}

func (m *Cluster) GetTransportSocket() *core.TransportSocket {
	if m != nil {
		return m.TransportSocket
	}
	return nil
}

func (m *Cluster) GetMetadata() *core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Cluster) GetProtocolSelection() Cluster_ClusterProtocolSelection {
	if m != nil {
		return m.ProtocolSelection
	}
	return Cluster_USE_CONFIGURED_PROTOCOL
}

func (m *Cluster) GetUpstreamConnectionOptions() *UpstreamConnectionOptions {
	if m != nil {
		return m.UpstreamConnectionOptions
	}
	return nil
}

func (m *Cluster) GetCloseConnectionsOnHostHealthFailure() bool {
	if m != nil {
		return m.CloseConnectionsOnHostHealthFailure
	}
	return false
}

func (m *Cluster) GetDrainConnectionsOnHostRemoval() bool {
	if m != nil {
		return m.DrainConnectionsOnHostRemoval
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Cluster) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Cluster_RingHashLbConfig_)(nil),
		(*Cluster_OriginalDstLbConfig_)(nil),
		(*Cluster_LeastRequestLbConfig_)(nil),
	}
}

// Only valid when discovery type is EDS.
type Cluster_EdsClusterConfig struct {
	// Configuration for the source of EDS updates for this Cluster.
	EdsConfig *core.ConfigSource `protobuf:"bytes,1,opt,name=eds_config,json=edsConfig,proto3" json:"eds_config,omitempty"`
	// Optional alternative to cluster name to present to EDS. This does not
	// have the same restrictions as cluster name, i.e. it may be arbitrary
	// length.
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_EdsClusterConfig) Reset()         { *m = Cluster_EdsClusterConfig{} }
func (m *Cluster_EdsClusterConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_EdsClusterConfig) ProtoMessage()    {}
func (*Cluster_EdsClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 0}
}

func (m *Cluster_EdsClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_EdsClusterConfig.Unmarshal(m, b)
}
func (m *Cluster_EdsClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_EdsClusterConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_EdsClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_EdsClusterConfig.Merge(m, src)
}
func (m *Cluster_EdsClusterConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_EdsClusterConfig.Size(m)
}
func (m *Cluster_EdsClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_EdsClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_EdsClusterConfig proto.InternalMessageInfo

func (m *Cluster_EdsClusterConfig) GetEdsConfig() *core.ConfigSource {
	if m != nil {
		return m.EdsConfig
	}
	return nil
}

func (m *Cluster_EdsClusterConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// Optionally divide the endpoints in this cluster into subsets defined by
// endpoint metadata and selected by route and weighted cluster metadata.
type Cluster_LbSubsetConfig struct {
	// The behavior used when no endpoint subset matches the selected route's
	// metadata. The value defaults to
	// :ref:`NO_FALLBACK<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.NO_FALLBACK>`.
	FallbackPolicy Cluster_LbSubsetConfig_LbSubsetFallbackPolicy `protobuf:"varint,1,opt,name=fallback_policy,json=fallbackPolicy,proto3,enum=envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy" json:"fallback_policy,omitempty"`
	// Specifies the default subset of endpoints used during fallback if
	// fallback_policy is
	// :ref:`DEFAULT_SUBSET<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.DEFAULT_SUBSET>`.
	// Each field in default_subset is
	// compared to the matching LbEndpoint.Metadata under the *envoy.lb*
	// namespace. It is valid for no hosts to match, in which case the behavior
	// is the same as a fallback_policy of
	// :ref:`NO_FALLBACK<envoy_api_enum_value_Cluster.LbSubsetConfig.LbSubsetFallbackPolicy.NO_FALLBACK>`.
	DefaultSubset *_struct.Struct `protobuf:"bytes,2,opt,name=default_subset,json=defaultSubset,proto3" json:"default_subset,omitempty"`
	// For each entry, LbEndpoint.Metadata's
	// *envoy.lb* namespace is traversed and a subset is created for each unique
	// combination of key and value. For example:
	//
	// .. code-block:: json
	//
	//   { "subset_selectors": [
	//       { "keys": [ "version" ] },
	//       { "keys": [ "stage", "hardware_type" ] }
	//   ]}
	//
	// A subset is matched when the metadata from the selected route and
	// weighted cluster contains the same keys and values as the subset's
	// metadata. The same host may appear in multiple subsets.
	SubsetSelectors []*Cluster_LbSubsetConfig_LbSubsetSelector `protobuf:"bytes,3,rep,name=subset_selectors,json=subsetSelectors,proto3" json:"subset_selectors,omitempty"`
	// If true, routing to subsets will take into account the localities and locality weights of the
	// endpoints when making the routing decision.
	//
	// There are some potential pitfalls associated with enabling this feature, as the resulting
	// traffic split after applying both a subset match and locality weights might be undesirable.
	//
	// Consider for example a situation in which you have 50/50 split across two localities X/Y
	// which have 100 hosts each without subsetting. If the subset LB results in X having only 1
	// host selected but Y having 100, then a lot more load is being dumped on the single host in X
	// than originally anticipated in the load balancing assignment delivered via EDS.
	LocalityWeightAware bool `protobuf:"varint,4,opt,name=locality_weight_aware,json=localityWeightAware,proto3" json:"locality_weight_aware,omitempty"`
	// When used with locality_weight_aware, scales the weight of each locality by the ratio
	// of hosts in the subset vs hosts in the original subset. This aims to even out the load
	// going to an individual locality if said locality is disproportionally affected by the
	// subset predicate.
	ScaleLocalityWeight  bool     `protobuf:"varint,5,opt,name=scale_locality_weight,json=scaleLocalityWeight,proto3" json:"scale_locality_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_LbSubsetConfig) Reset()         { *m = Cluster_LbSubsetConfig{} }
func (m *Cluster_LbSubsetConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig) ProtoMessage()    {}
func (*Cluster_LbSubsetConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 3}
}

func (m *Cluster_LbSubsetConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_LbSubsetConfig.Unmarshal(m, b)
}
func (m *Cluster_LbSubsetConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_LbSubsetConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_LbSubsetConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_LbSubsetConfig.Merge(m, src)
}
func (m *Cluster_LbSubsetConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_LbSubsetConfig.Size(m)
}
func (m *Cluster_LbSubsetConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_LbSubsetConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_LbSubsetConfig proto.InternalMessageInfo

func (m *Cluster_LbSubsetConfig) GetFallbackPolicy() Cluster_LbSubsetConfig_LbSubsetFallbackPolicy {
	if m != nil {
		return m.FallbackPolicy
	}
	return Cluster_LbSubsetConfig_NO_FALLBACK
}

func (m *Cluster_LbSubsetConfig) GetDefaultSubset() *_struct.Struct {
	if m != nil {
		return m.DefaultSubset
	}
	return nil
}

func (m *Cluster_LbSubsetConfig) GetSubsetSelectors() []*Cluster_LbSubsetConfig_LbSubsetSelector {
	if m != nil {
		return m.SubsetSelectors
	}
	return nil
}

func (m *Cluster_LbSubsetConfig) GetLocalityWeightAware() bool {
	if m != nil {
		return m.LocalityWeightAware
	}
	return false
}

func (m *Cluster_LbSubsetConfig) GetScaleLocalityWeight() bool {
	if m != nil {
		return m.ScaleLocalityWeight
	}
	return false
}

// Specifications for subsets.
type Cluster_LbSubsetConfig_LbSubsetSelector struct {
	// List of keys to match with the weighted cluster metadata.
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) Reset() {
	*m = Cluster_LbSubsetConfig_LbSubsetSelector{}
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) String() string { return proto.CompactTextString(m) }
func (*Cluster_LbSubsetConfig_LbSubsetSelector) ProtoMessage()    {}
func (*Cluster_LbSubsetConfig_LbSubsetSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 3, 0}
}

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector.Unmarshal(m, b)
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector.Marshal(b, m, deterministic)
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector.Merge(m, src)
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) XXX_Size() int {
	return xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector.Size(m)
}
func (m *Cluster_LbSubsetConfig_LbSubsetSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_LbSubsetConfig_LbSubsetSelector proto.InternalMessageInfo

func (m *Cluster_LbSubsetConfig_LbSubsetSelector) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Specific configuration for the LeastRequest load balancing policy.
type Cluster_LeastRequestLbConfig struct {
	// The number of random healthy hosts from which the host with the fewest active requests will
	// be chosen. Defaults to 2 so that we perform two-choice selection if the field is not set.
	ChoiceCount          *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=choice_count,json=choiceCount,proto3" json:"choice_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Cluster_LeastRequestLbConfig) Reset()         { *m = Cluster_LeastRequestLbConfig{} }
func (m *Cluster_LeastRequestLbConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_LeastRequestLbConfig) ProtoMessage()    {}
func (*Cluster_LeastRequestLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 4}
}

func (m *Cluster_LeastRequestLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_LeastRequestLbConfig.Unmarshal(m, b)
}
func (m *Cluster_LeastRequestLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_LeastRequestLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_LeastRequestLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_LeastRequestLbConfig.Merge(m, src)
}
func (m *Cluster_LeastRequestLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_LeastRequestLbConfig.Size(m)
}
func (m *Cluster_LeastRequestLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_LeastRequestLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_LeastRequestLbConfig proto.InternalMessageInfo

func (m *Cluster_LeastRequestLbConfig) GetChoiceCount() *wrappers.UInt32Value {
	if m != nil {
		return m.ChoiceCount
	}
	return nil
}

// Specific configuration for the :ref:`RingHash<arch_overview_load_balancing_types_ring_hash>`
// load balancing policy.
type Cluster_RingHashLbConfig struct {
	// Minimum hash ring size. The larger the ring is (that is, the more hashes there are for each
	// provided host) the better the request distribution will reflect the desired weights. Defaults
	// to 1024 entries, and limited to 8M entries. See also
	// :ref:`maximum_ring_size<envoy_api_field_Cluster.RingHashLbConfig.maximum_ring_size>`.
	MinimumRingSize *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=minimum_ring_size,json=minimumRingSize,proto3" json:"minimum_ring_size,omitempty"`
	// Deprecated settings from v1 config.
	// [#not-implemented-hide:] Hide from docs.
	DeprecatedV1 *Cluster_RingHashLbConfig_DeprecatedV1 `protobuf:"bytes,2,opt,name=deprecated_v1,json=deprecatedV1,proto3" json:"deprecated_v1,omitempty"` // Deprecated: Do not use.
	// The hash function used to hash hosts onto the ketama ring. The value defaults to
	// :ref:`XX_HASH<envoy_api_enum_value_Cluster.RingHashLbConfig.HashFunction.XX_HASH>`.
	HashFunction Cluster_RingHashLbConfig_HashFunction `protobuf:"varint,3,opt,name=hash_function,json=hashFunction,proto3,enum=envoy.api.v2.Cluster_RingHashLbConfig_HashFunction" json:"hash_function,omitempty"`
	// Maximum hash ring size. Defaults to 8M entries, and limited to 8M entries, but can be lowered
	// to further constrain resource use. See also
	// :ref:`minimum_ring_size<envoy_api_field_Cluster.RingHashLbConfig.minimum_ring_size>`.
	MaximumRingSize      *wrappers.UInt64Value `protobuf:"bytes,4,opt,name=maximum_ring_size,json=maximumRingSize,proto3" json:"maximum_ring_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Cluster_RingHashLbConfig) Reset()         { *m = Cluster_RingHashLbConfig{} }
func (m *Cluster_RingHashLbConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_RingHashLbConfig) ProtoMessage()    {}
func (*Cluster_RingHashLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 5}
}

func (m *Cluster_RingHashLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_RingHashLbConfig.Unmarshal(m, b)
}
func (m *Cluster_RingHashLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_RingHashLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_RingHashLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_RingHashLbConfig.Merge(m, src)
}
func (m *Cluster_RingHashLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_RingHashLbConfig.Size(m)
}
func (m *Cluster_RingHashLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_RingHashLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_RingHashLbConfig proto.InternalMessageInfo

func (m *Cluster_RingHashLbConfig) GetMinimumRingSize() *wrappers.UInt64Value {
	if m != nil {
		return m.MinimumRingSize
	}
	return nil
}

// Deprecated: Do not use.
func (m *Cluster_RingHashLbConfig) GetDeprecatedV1() *Cluster_RingHashLbConfig_DeprecatedV1 {
	if m != nil {
		return m.DeprecatedV1
	}
	return nil
}

func (m *Cluster_RingHashLbConfig) GetHashFunction() Cluster_RingHashLbConfig_HashFunction {
	if m != nil {
		return m.HashFunction
	}
	return Cluster_RingHashLbConfig_XX_HASH
}

func (m *Cluster_RingHashLbConfig) GetMaximumRingSize() *wrappers.UInt64Value {
	if m != nil {
		return m.MaximumRingSize
	}
	return nil
}

// [#not-implemented-hide:] Hide from docs.
type Cluster_RingHashLbConfig_DeprecatedV1 struct {
	// Defaults to false, meaning that `xxHash <https://github.com/Cyan4973/xxHash>`_
	// is to hash hosts onto the ketama ring.
	UseStdHash           *wrappers.BoolValue `protobuf:"bytes,1,opt,name=use_std_hash,json=useStdHash,proto3" json:"use_std_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Cluster_RingHashLbConfig_DeprecatedV1) Reset()         { *m = Cluster_RingHashLbConfig_DeprecatedV1{} }
func (m *Cluster_RingHashLbConfig_DeprecatedV1) String() string { return proto.CompactTextString(m) }
func (*Cluster_RingHashLbConfig_DeprecatedV1) ProtoMessage()    {}
func (*Cluster_RingHashLbConfig_DeprecatedV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 5, 0}
}

func (m *Cluster_RingHashLbConfig_DeprecatedV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1.Unmarshal(m, b)
}
func (m *Cluster_RingHashLbConfig_DeprecatedV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1.Marshal(b, m, deterministic)
}
func (m *Cluster_RingHashLbConfig_DeprecatedV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1.Merge(m, src)
}
func (m *Cluster_RingHashLbConfig_DeprecatedV1) XXX_Size() int {
	return xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1.Size(m)
}
func (m *Cluster_RingHashLbConfig_DeprecatedV1) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_RingHashLbConfig_DeprecatedV1 proto.InternalMessageInfo

func (m *Cluster_RingHashLbConfig_DeprecatedV1) GetUseStdHash() *wrappers.BoolValue {
	if m != nil {
		return m.UseStdHash
	}
	return nil
}

// Specific configuration for the
// :ref:`Original Destination <arch_overview_load_balancing_types_original_destination>`
// load balancing policy.
type Cluster_OriginalDstLbConfig struct {
	// When true, :ref:`x-envoy-original-dst-host
	// <config_http_conn_man_headers_x-envoy-original-dst-host>` can be used to override destination
	// address.
	//
	// .. attention::
	//
	//   This header isn't sanitized by default, so enabling this feature allows HTTP clients to
	//   route traffic to arbitrary hosts and/or ports, which may have serious security
	//   consequences.
	UseHttpHeader        bool     `protobuf:"varint,1,opt,name=use_http_header,json=useHttpHeader,proto3" json:"use_http_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_OriginalDstLbConfig) Reset()         { *m = Cluster_OriginalDstLbConfig{} }
func (m *Cluster_OriginalDstLbConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_OriginalDstLbConfig) ProtoMessage()    {}
func (*Cluster_OriginalDstLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 6}
}

func (m *Cluster_OriginalDstLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_OriginalDstLbConfig.Unmarshal(m, b)
}
func (m *Cluster_OriginalDstLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_OriginalDstLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_OriginalDstLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_OriginalDstLbConfig.Merge(m, src)
}
func (m *Cluster_OriginalDstLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_OriginalDstLbConfig.Size(m)
}
func (m *Cluster_OriginalDstLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_OriginalDstLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_OriginalDstLbConfig proto.InternalMessageInfo

func (m *Cluster_OriginalDstLbConfig) GetUseHttpHeader() bool {
	if m != nil {
		return m.UseHttpHeader
	}
	return false
}

// Common configuration for all load balancer implementations.
type Cluster_CommonLbConfig struct {
	// Configures the :ref:`healthy panic threshold <arch_overview_load_balancing_panic_threshold>`.
	// If not specified, the default is 50%.
	//
	// .. note::
	//   The specified percent will be truncated to the nearest 1%.
	HealthyPanicThreshold *_type.Percent `protobuf:"bytes,1,opt,name=healthy_panic_threshold,json=healthyPanicThreshold,proto3" json:"healthy_panic_threshold,omitempty"`
	// Types that are valid to be assigned to LocalityConfigSpecifier:
	//	*Cluster_CommonLbConfig_ZoneAwareLbConfig_
	//	*Cluster_CommonLbConfig_LocalityWeightedLbConfig_
	LocalityConfigSpecifier isCluster_CommonLbConfig_LocalityConfigSpecifier `protobuf_oneof:"locality_config_specifier"`
	// If set, all health check/weight/metadata updates that happen within this duration will be
	// merged and delivered in one shot when the duration expires. The start of the duration is when
	// the first update happens. This is useful for big clusters, with potentially noisy deploys
	// that might trigger excessive CPU usage due to a constant stream of healthcheck state changes
	// or metadata updates. The first set of updates to be seen apply immediately (e.g.: a new
	// cluster).
	//
	// If this is not set, we default to a merge window of 1000ms. To disable it, set the merge
	// window to 0.
	//
	// Note: merging does not apply to cluster membership changes (e.g.: adds/removes); this is
	// because merging those updates isn't currently safe. See
	// https://github.com/envoyproxy/envoy/pull/3941.
	UpdateMergeWindow    *duration.Duration `protobuf:"bytes,4,opt,name=update_merge_window,json=updateMergeWindow,proto3" json:"update_merge_window,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Cluster_CommonLbConfig) Reset()         { *m = Cluster_CommonLbConfig{} }
func (m *Cluster_CommonLbConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_CommonLbConfig) ProtoMessage()    {}
func (*Cluster_CommonLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 7}
}

func (m *Cluster_CommonLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_CommonLbConfig.Unmarshal(m, b)
}
func (m *Cluster_CommonLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_CommonLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_CommonLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_CommonLbConfig.Merge(m, src)
}
func (m *Cluster_CommonLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_CommonLbConfig.Size(m)
}
func (m *Cluster_CommonLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_CommonLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_CommonLbConfig proto.InternalMessageInfo

func (m *Cluster_CommonLbConfig) GetHealthyPanicThreshold() *_type.Percent {
	if m != nil {
		return m.HealthyPanicThreshold
	}
	return nil
}

type isCluster_CommonLbConfig_LocalityConfigSpecifier interface {
	isCluster_CommonLbConfig_LocalityConfigSpecifier()
}

type Cluster_CommonLbConfig_ZoneAwareLbConfig_ struct {
	ZoneAwareLbConfig *Cluster_CommonLbConfig_ZoneAwareLbConfig `protobuf:"bytes,2,opt,name=zone_aware_lb_config,json=zoneAwareLbConfig,proto3,oneof"`
}

type Cluster_CommonLbConfig_LocalityWeightedLbConfig_ struct {
	LocalityWeightedLbConfig *Cluster_CommonLbConfig_LocalityWeightedLbConfig `protobuf:"bytes,3,opt,name=locality_weighted_lb_config,json=localityWeightedLbConfig,proto3,oneof"`
}

func (*Cluster_CommonLbConfig_ZoneAwareLbConfig_) isCluster_CommonLbConfig_LocalityConfigSpecifier() {}

func (*Cluster_CommonLbConfig_LocalityWeightedLbConfig_) isCluster_CommonLbConfig_LocalityConfigSpecifier() {
}

func (m *Cluster_CommonLbConfig) GetLocalityConfigSpecifier() isCluster_CommonLbConfig_LocalityConfigSpecifier {
	if m != nil {
		return m.LocalityConfigSpecifier
	}
	return nil
}

func (m *Cluster_CommonLbConfig) GetZoneAwareLbConfig() *Cluster_CommonLbConfig_ZoneAwareLbConfig {
	if x, ok := m.GetLocalityConfigSpecifier().(*Cluster_CommonLbConfig_ZoneAwareLbConfig_); ok {
		return x.ZoneAwareLbConfig
	}
	return nil
}

func (m *Cluster_CommonLbConfig) GetLocalityWeightedLbConfig() *Cluster_CommonLbConfig_LocalityWeightedLbConfig {
	if x, ok := m.GetLocalityConfigSpecifier().(*Cluster_CommonLbConfig_LocalityWeightedLbConfig_); ok {
		return x.LocalityWeightedLbConfig
	}
	return nil
}

func (m *Cluster_CommonLbConfig) GetUpdateMergeWindow() *duration.Duration {
	if m != nil {
		return m.UpdateMergeWindow
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Cluster_CommonLbConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Cluster_CommonLbConfig_ZoneAwareLbConfig_)(nil),
		(*Cluster_CommonLbConfig_LocalityWeightedLbConfig_)(nil),
	}
}

// Configuration for :ref:`zone aware routing
// <arch_overview_load_balancing_zone_aware_routing>`.
type Cluster_CommonLbConfig_ZoneAwareLbConfig struct {
	// Configures percentage of requests that will be considered for zone aware routing
	// if zone aware routing is configured. If not specified, the default is 100%.
	// * :ref:`runtime values <config_cluster_manager_cluster_runtime_zone_routing>`.
	// * :ref:`Zone aware routing support <arch_overview_load_balancing_zone_aware_routing>`.
	RoutingEnabled *_type.Percent `protobuf:"bytes,1,opt,name=routing_enabled,json=routingEnabled,proto3" json:"routing_enabled,omitempty"`
	// Configures minimum upstream cluster size required for zone aware routing
	// If upstream cluster size is less than specified, zone aware routing is not performed
	// even if zone aware routing is configured. If not specified, the default is 6.
	// * :ref:`runtime values <config_cluster_manager_cluster_runtime_zone_routing>`.
	// * :ref:`Zone aware routing support <arch_overview_load_balancing_zone_aware_routing>`.
	MinClusterSize       *wrappers.UInt64Value `protobuf:"bytes,2,opt,name=min_cluster_size,json=minClusterSize,proto3" json:"min_cluster_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) Reset() {
	*m = Cluster_CommonLbConfig_ZoneAwareLbConfig{}
}
func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) String() string { return proto.CompactTextString(m) }
func (*Cluster_CommonLbConfig_ZoneAwareLbConfig) ProtoMessage()    {}
func (*Cluster_CommonLbConfig_ZoneAwareLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 7, 0}
}

func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig.Unmarshal(m, b)
}
func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig.Merge(m, src)
}
func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig.Size(m)
}
func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_CommonLbConfig_ZoneAwareLbConfig proto.InternalMessageInfo

func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) GetRoutingEnabled() *_type.Percent {
	if m != nil {
		return m.RoutingEnabled
	}
	return nil
}

func (m *Cluster_CommonLbConfig_ZoneAwareLbConfig) GetMinClusterSize() *wrappers.UInt64Value {
	if m != nil {
		return m.MinClusterSize
	}
	return nil
}

// Configuration for :ref:`locality weighted load balancing
// <arch_overview_load_balancing_locality_weighted_lb>`
type Cluster_CommonLbConfig_LocalityWeightedLbConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) Reset() {
	*m = Cluster_CommonLbConfig_LocalityWeightedLbConfig{}
}
func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) String() string {
	return proto.CompactTextString(m)
}
func (*Cluster_CommonLbConfig_LocalityWeightedLbConfig) ProtoMessage() {}
func (*Cluster_CommonLbConfig_LocalityWeightedLbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{0, 7, 1}
}

func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig.Unmarshal(m, b)
}
func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig.Marshal(b, m, deterministic)
}
func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig.Merge(m, src)
}
func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) XXX_Size() int {
	return xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig.Size(m)
}
func (m *Cluster_CommonLbConfig_LocalityWeightedLbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster_CommonLbConfig_LocalityWeightedLbConfig proto.InternalMessageInfo

// An extensible structure containing the address Envoy should bind to when
// establishing upstream connections.
type UpstreamBindConfig struct {
	// The address Envoy should bind to when establishing upstream connections.
	SourceAddress        *core.Address `protobuf:"bytes,1,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpstreamBindConfig) Reset()         { *m = UpstreamBindConfig{} }
func (m *UpstreamBindConfig) String() string { return proto.CompactTextString(m) }
func (*UpstreamBindConfig) ProtoMessage()    {}
func (*UpstreamBindConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{1}
}

func (m *UpstreamBindConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamBindConfig.Unmarshal(m, b)
}
func (m *UpstreamBindConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamBindConfig.Marshal(b, m, deterministic)
}
func (m *UpstreamBindConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamBindConfig.Merge(m, src)
}
func (m *UpstreamBindConfig) XXX_Size() int {
	return xxx_messageInfo_UpstreamBindConfig.Size(m)
}
func (m *UpstreamBindConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamBindConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamBindConfig proto.InternalMessageInfo

func (m *UpstreamBindConfig) GetSourceAddress() *core.Address {
	if m != nil {
		return m.SourceAddress
	}
	return nil
}

type UpstreamConnectionOptions struct {
	// If set then set SO_KEEPALIVE on the socket to enable TCP Keepalives.
	TcpKeepalive         *core.TcpKeepalive `protobuf:"bytes,1,opt,name=tcp_keepalive,json=tcpKeepalive,proto3" json:"tcp_keepalive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpstreamConnectionOptions) Reset()         { *m = UpstreamConnectionOptions{} }
func (m *UpstreamConnectionOptions) String() string { return proto.CompactTextString(m) }
func (*UpstreamConnectionOptions) ProtoMessage()    {}
func (*UpstreamConnectionOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d26968b30a0ff7a, []int{2}
}

func (m *UpstreamConnectionOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamConnectionOptions.Unmarshal(m, b)
}
func (m *UpstreamConnectionOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamConnectionOptions.Marshal(b, m, deterministic)
}
func (m *UpstreamConnectionOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamConnectionOptions.Merge(m, src)
}
func (m *UpstreamConnectionOptions) XXX_Size() int {
	return xxx_messageInfo_UpstreamConnectionOptions.Size(m)
}
func (m *UpstreamConnectionOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamConnectionOptions.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamConnectionOptions proto.InternalMessageInfo

func (m *UpstreamConnectionOptions) GetTcpKeepalive() *core.TcpKeepalive {
	if m != nil {
		return m.TcpKeepalive
	}
	return nil
}

func init() {
	proto.RegisterEnum("envoy.api.v2.Cluster_DiscoveryType", Cluster_DiscoveryType_name, Cluster_DiscoveryType_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbPolicy", Cluster_LbPolicy_name, Cluster_LbPolicy_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_DnsLookupFamily", Cluster_DnsLookupFamily_name, Cluster_DnsLookupFamily_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_ClusterProtocolSelection", Cluster_ClusterProtocolSelection_name, Cluster_ClusterProtocolSelection_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_LbSubsetConfig_LbSubsetFallbackPolicy", Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_name, Cluster_LbSubsetConfig_LbSubsetFallbackPolicy_value)
	proto.RegisterEnum("envoy.api.v2.Cluster_RingHashLbConfig_HashFunction", Cluster_RingHashLbConfig_HashFunction_name, Cluster_RingHashLbConfig_HashFunction_value)
	proto.RegisterType((*Cluster)(nil), "envoy.api.v2.Cluster")
	proto.RegisterMapType((map[string]*_struct.Struct)(nil), "envoy.api.v2.Cluster.ExtensionProtocolOptionsEntry")
	proto.RegisterMapType((map[string]*any.Any)(nil), "envoy.api.v2.Cluster.TypedExtensionProtocolOptionsEntry")
	proto.RegisterType((*Cluster_EdsClusterConfig)(nil), "envoy.api.v2.Cluster.EdsClusterConfig")
	proto.RegisterType((*Cluster_LbSubsetConfig)(nil), "envoy.api.v2.Cluster.LbSubsetConfig")
	proto.RegisterType((*Cluster_LbSubsetConfig_LbSubsetSelector)(nil), "envoy.api.v2.Cluster.LbSubsetConfig.LbSubsetSelector")
	proto.RegisterType((*Cluster_LeastRequestLbConfig)(nil), "envoy.api.v2.Cluster.LeastRequestLbConfig")
	proto.RegisterType((*Cluster_RingHashLbConfig)(nil), "envoy.api.v2.Cluster.RingHashLbConfig")
	proto.RegisterType((*Cluster_RingHashLbConfig_DeprecatedV1)(nil), "envoy.api.v2.Cluster.RingHashLbConfig.DeprecatedV1")
	proto.RegisterType((*Cluster_OriginalDstLbConfig)(nil), "envoy.api.v2.Cluster.OriginalDstLbConfig")
	proto.RegisterType((*Cluster_CommonLbConfig)(nil), "envoy.api.v2.Cluster.CommonLbConfig")
	proto.RegisterType((*Cluster_CommonLbConfig_ZoneAwareLbConfig)(nil), "envoy.api.v2.Cluster.CommonLbConfig.ZoneAwareLbConfig")
	proto.RegisterType((*Cluster_CommonLbConfig_LocalityWeightedLbConfig)(nil), "envoy.api.v2.Cluster.CommonLbConfig.LocalityWeightedLbConfig")
	proto.RegisterType((*UpstreamBindConfig)(nil), "envoy.api.v2.UpstreamBindConfig")
	proto.RegisterType((*UpstreamConnectionOptions)(nil), "envoy.api.v2.UpstreamConnectionOptions")
}

func init() { proto.RegisterFile("cds.proto", fileDescriptor_5d26968b30a0ff7a) }

var fileDescriptor_5d26968b30a0ff7a = []byte{
	// 2542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0xcd, 0x73, 0x23, 0x47,
	0x15, 0xf7, 0xc8, 0xda, 0xac, 0xdd, 0xd6, 0xc7, 0xb8, 0xed, 0xdd, 0x9d, 0x95, 0xd7, 0xbb, 0x5e,
	0x25, 0x1b, 0x8c, 0x0b, 0x64, 0xe2, 0x4d, 0x42, 0x2a, 0x24, 0xa1, 0xf4, 0xe5, 0xb5, 0x13, 0x59,
	0x32, 0x23, 0x79, 0x9d, 0x10, 0x52, 0x9d, 0xd6, 0x4c, 0x4b, 0x1a, 0x3c, 0x9a, 0x19, 0xa6, 0x7b,
	0xbc, 0xab, 0x3d, 0x50, 0x21, 0x05, 0x55, 0xdc, 0xb9, 0xc0, 0x7f, 0x40, 0xf1, 0x27, 0x70, 0x81,
	0x23, 0x77, 0x8e, 0x54, 0x41, 0x15, 0xc5, 0x01, 0xfe, 0x0b, 0xaa, 0x3f, 0x46, 0xab, 0x8f, 0x91,
	0xd7, 0xa1, 0x38, 0x59, 0xfd, 0xde, 0xef, 0xfd, 0x5e, 0xf7, 0x9b, 0xee, 0xf7, 0x5e, 0xb7, 0xc1,
	0xaa, 0x65, 0xd3, 0x52, 0x10, 0xfa, 0xcc, 0x87, 0x19, 0xe2, 0x5d, 0xfa, 0xa3, 0x12, 0x0e, 0x9c,
	0xd2, 0xe5, 0x41, 0xe1, 0x81, 0x18, 0xed, 0xe3, 0xc0, 0xd9, 0xbf, 0x3c, 0xd8, 0xb7, 0xfc, 0x90,
	0xec, 0x63, 0xdb, 0x0e, 0x09, 0x55, 0xf0, 0xc2, 0xbd, 0x29, 0x00, 0x8e, 0xd8, 0x60, 0xdf, 0x22,
	0x21, 0x4b, 0xd4, 0x0a, 0xf3, 0x2e, 0xa6, 0x44, 0x69, 0x1f, 0xcd, 0x6b, 0x2d, 0xdf, 0xeb, 0x39,
	0x7d, 0x44, 0xfd, 0x28, 0xb4, 0x48, 0x22, 0x89, 0xed, 0x50, 0xcb, 0xbf, 0x24, 0xe1, 0x48, 0x69,
	0xdf, 0x98, 0x27, 0x19, 0x10, 0xec, 0xb2, 0x01, 0xb2, 0x06, 0xc4, 0xba, 0x50, 0xa8, 0x9d, 0x79,
	0x94, 0x50, 0x58, 0xbe, 0xab, 0x10, 0x7b, 0xd3, 0x08, 0x37, 0xa2, 0x8c, 0x84, 0xfb, 0x96, 0x13,
	0x5a, 0x91, 0xc3, 0x50, 0x37, 0x24, 0xf8, 0x82, 0x84, 0x0a, 0xfb, 0x9d, 0x44, 0xac, 0x1f, 0x31,
	0xd7, 0x21, 0x21, 0xb2, 0x09, 0x23, 0x16, 0x73, 0x7c, 0x4f, 0xa1, 0x6f, 0x4f, 0xa1, 0x49, 0x1c,
	0xe9, 0x82, 0x21, 0xe5, 0x6c, 0x14, 0x90, 0xfd, 0x80, 0x84, 0x16, 0xf1, 0xc6, 0x61, 0xeb, 0xfb,
	0x7e, 0xdf, 0x25, 0xc2, 0x04, 0x7b, 0x9e, 0xcf, 0x30, 0xa7, 0x8b, 0xed, 0xee, 0x2a, 0xad, 0x18,
	0x75, 0xa3, 0xde, 0x3e, 0xf6, 0xe2, 0x60, 0xdc, 0x9f, 0x55, 0xd9, 0x51, 0x88, 0x27, 0xa6, 0x72,
	0x6f, 0x56, 0x4f, 0x59, 0x18, 0x59, 0x6c, 0x91, 0xf5, 0xb3, 0x10, 0x07, 0x01, 0x09, 0x63, 0xc7,
	0x77, 0x2e, 0xb1, 0xeb, 0xd8, 0x98, 0x91, 0xfd, 0xf8, 0x87, 0x52, 0x6c, 0xf6, 0xfd, 0xbe, 0x2f,
	0x7e, 0xee, 0xf3, 0x5f, 0x52, 0x5a, 0xfc, 0xd3, 0x1e, 0xb8, 0x59, 0x95, 0xb1, 0x81, 0xdb, 0x20,
	0xed, 0xe1, 0x21, 0x31, 0xb4, 0x1d, 0x6d, 0x77, 0xb5, 0xb2, 0xfa, 0xc7, 0xff, 0xfc, 0x79, 0x39,
	0x1d, 0xa6, 0x76, 0x34, 0x53, 0x88, 0x61, 0x11, 0x64, 0xb1, 0xcb, 0x10, 0x65, 0x98, 0x21, 0x81,
	0xbb, 0xc7, 0x71, 0xe6, 0x1a, 0x76, 0x59, 0x9b, 0x61, 0xd6, 0xe4, 0x98, 0x2a, 0x48, 0xf3, 0x50,
	0x19, 0xa9, 0x1d, 0x6d, 0x37, 0x77, 0xf0, 0x7a, 0x69, 0x72, 0x9f, 0x96, 0x94, 0x9f, 0x52, 0x2d,
	0xde, 0x1d, 0x9d, 0x51, 0x40, 0x2a, 0x80, 0xfb, 0xb9, 0xf1, 0xb5, 0x96, 0xd2, 0x35, 0x53, 0x18,
	0xc3, 0x0e, 0x80, 0xc4, 0xa6, 0x48, 0x7d, 0x32, 0x24, 0xb7, 0x9b, 0xb1, 0xbc, 0xa3, 0xed, 0xae,
	0x1d, 0xbc, 0x99, 0x4c, 0x59, 0xb7, 0xa9, 0xfa, 0x59, 0x15, 0x68, 0x53, 0x27, 0x33, 0x12, 0xf8,
	0x14, 0xe4, 0x2d, 0xdf, 0xf3, 0x88, 0xc5, 0x10, 0x73, 0x86, 0xc4, 0x8f, 0x98, 0x91, 0x16, 0x94,
	0x77, 0x4b, 0x32, 0xa4, 0xa5, 0x38, 0xa4, 0xa5, 0x9a, 0xfa, 0x20, 0x15, 0xf8, 0x97, 0xbf, 0x3f,
	0x58, 0xfa, 0xed, 0x3f, 0x1e, 0x68, 0x62, 0x8e, 0x7f, 0xd0, 0x52, 0x7b, 0x4b, 0x66, 0x4e, 0xb1,
	0x74, 0x24, 0x09, 0xec, 0x81, 0x87, 0x81, 0x9c, 0xa5, 0x27, 0x77, 0x14, 0xea, 0x46, 0xbd, 0x1e,
	0x09, 0x91, 0xeb, 0x0c, 0xf9, 0xa6, 0x1c, 0x31, 0x42, 0x8d, 0x1b, 0xc2, 0xd3, 0xbd, 0x39, 0x4f,
	0x67, 0xc7, 0x1e, 0x7b, 0x7c, 0xf0, 0x14, 0xbb, 0x11, 0x31, 0xb7, 0x03, 0x31, 0x57, 0xc5, 0x52,
	0x11, 0x24, 0x0d, 0xce, 0x51, 0xe1, 0x14, 0xf0, 0x09, 0x58, 0x75, 0xbb, 0x28, 0xf0, 0x5d, 0xc7,
	0x1a, 0x19, 0xaf, 0x89, 0xf8, 0xde, 0x4f, 0x0e, 0x46, 0xa3, 0x7b, 0x2a, 0x50, 0x53, 0xa1, 0x5d,
	0x71, 0x95, 0x14, 0xbe, 0x0d, 0x6e, 0x0c, 0x7c, 0xca, 0xa8, 0x71, 0x73, 0x67, 0x79, 0x77, 0xed,
	0xa0, 0x30, 0x4d, 0xc2, 0x8f, 0x5d, 0xa9, 0x2c, 0xd3, 0x47, 0x25, 0x65, 0x68, 0xa6, 0x04, 0xc3,
	0x06, 0xc8, 0xbb, 0x3e, 0xb6, 0x11, 0xa6, 0xd4, 0xe9, 0x7b, 0x43, 0xe2, 0x31, 0xe3, 0xa1, 0x58,
	0x54, 0xf2, 0x47, 0x6e, 0xf8, 0xd8, 0x2e, 0x8f, 0xa1, 0x66, 0xce, 0x9d, 0x1a, 0xc3, 0x2a, 0xc8,
	0x4e, 0x26, 0x00, 0x6a, 0xac, 0x88, 0xb9, 0xdc, 0x4f, 0x98, 0xcb, 0x91, 0xc0, 0x55, 0x39, 0xcc,
	0xcc, 0x0c, 0x5e, 0x0e, 0x28, 0xfc, 0x1c, 0x6c, 0x0d, 0xf1, 0x73, 0x14, 0x92, 0x9f, 0x45, 0x84,
	0x32, 0x8a, 0xa6, 0x3f, 0x83, 0xb1, 0x7a, 0x8d, 0x98, 0x1b, 0x43, 0xfc, 0xdc, 0x54, 0xf6, 0xa7,
	0x93, 0xe1, 0x87, 0xa7, 0x40, 0x9f, 0xc9, 0x2b, 0xd4, 0x00, 0x82, 0xf1, 0xd1, 0xcc, 0x24, 0x55,
	0xd4, 0xab, 0x12, 0x5d, 0x51, 0x60, 0x33, 0x6f, 0x4d, 0x0b, 0xe0, 0x21, 0x58, 0x63, 0x2e, 0xe5,
	0x33, 0x64, 0xe4, 0x39, 0x33, 0xd6, 0x92, 0xc8, 0x78, 0x6e, 0x2e, 0x9d, 0x05, 0x94, 0x85, 0x04,
	0x0f, 0x3b, 0x2e, 0xad, 0x4a, 0xb0, 0x09, 0xd8, 0xf8, 0x37, 0xec, 0x83, 0x7b, 0x96, 0x3f, 0x1c,
	0xfa, 0x1e, 0x1a, 0x30, 0x16, 0xa0, 0x38, 0x45, 0x22, 0x3f, 0x10, 0x09, 0xc8, 0xd8, 0x4e, 0x3a,
	0x28, 0x32, 0x94, 0x8c, 0x05, 0xa7, 0x0a, 0xde, 0x92, 0x68, 0xf3, 0xae, 0xe4, 0x4a, 0x50, 0xc1,
	0xcf, 0xc1, 0xad, 0x64, 0x0f, 0x59, 0xe1, 0xe1, 0x5b, 0x0b, 0x3c, 0xbc, 0x35, 0xeb, 0x62, 0x63,
	0x90, 0x40, 0xfe, 0x05, 0xb8, 0xcd, 0xc5, 0x07, 0xf3, 0xec, 0xb9, 0x2b, 0xd9, 0x0f, 0x66, 0xd9,
	0x37, 0x07, 0x09, 0x52, 0x18, 0x81, 0x02, 0x79, 0xce, 0x88, 0x47, 0xf9, 0x81, 0x9c, 0x73, 0xf1,
	0xba, 0xd8, 0x6d, 0x8f, 0x17, 0xe4, 0x92, 0xd8, 0x6e, 0x86, 0xb3, 0xee, 0xb1, 0x70, 0x24, 0x8e,
	0x84, 0x41, 0x16, 0x40, 0xe0, 0x2f, 0x34, 0xb0, 0xc3, 0x73, 0x98, 0x8d, 0xae, 0xf0, 0xfe, 0x86,
	0xf0, 0xfe, 0x5e, 0xb2, 0x77, 0x9e, 0x13, 0xed, 0x2b, 0xa7, 0x60, 0x6e, 0xb3, 0xab, 0x30, 0xb0,
	0x0d, 0x74, 0xdb, 0xa3, 0x28, 0x24, 0xbd, 0x90, 0xd0, 0x01, 0x0a, 0x31, 0x23, 0x86, 0xfe, 0xaa,
	0x4c, 0x97, 0x9b, 0xcd, 0x72, 0xb6, 0x47, 0x4d, 0xc9, 0x60, 0x62, 0x46, 0xe0, 0x17, 0x60, 0x9d,
	0x93, 0xba, 0xbe, 0x7f, 0x11, 0x05, 0xa8, 0x87, 0x87, 0x8e, 0x3b, 0x32, 0xd6, 0x45, 0x16, 0x7a,
	0xb4, 0x20, 0xcb, 0x7b, 0xb4, 0x21, 0xd0, 0x87, 0x02, 0x3c, 0x95, 0x8c, 0xf2, 0xf6, 0xb4, 0x12,
	0xfe, 0x10, 0x64, 0xe5, 0x9c, 0xa9, 0xef, 0x5e, 0xf2, 0xa3, 0x06, 0x5f, 0x95, 0x9b, 0xcc, 0x8c,
	0x98, 0xa1, 0xc2, 0xc3, 0x36, 0x58, 0x9f, 0x2b, 0xed, 0xc6, 0x46, 0xe2, 0x49, 0x50, 0xf3, 0x6b,
	0x49, 0x78, 0x2d, 0x46, 0x9b, 0xba, 0x3f, 0x23, 0x81, 0x1d, 0xa0, 0x5b, 0x2e, 0xc1, 0x5e, 0x14,
	0x20, 0xc7, 0x63, 0x24, 0xbc, 0xc4, 0xae, 0xb1, 0xf9, 0x4d, 0x23, 0x99, 0x57, 0x14, 0xc7, 0x8a,
	0x01, 0xb6, 0xc0, 0x66, 0xa4, 0x4e, 0x38, 0xea, 0x3a, 0x9e, 0x1d, 0x17, 0xb8, 0x5b, 0x82, 0x79,
	0x3b, 0x61, 0xc9, 0x15, 0xc7, 0xb3, 0x55, 0x5d, 0x83, 0xb1, 0xe9, 0x4b, 0x19, 0x6c, 0x02, 0xdd,
	0xed, 0x22, 0x1a, 0x75, 0x29, 0x61, 0x31, 0xd9, 0x6d, 0x41, 0xf6, 0xc6, 0xa2, 0x02, 0xd1, 0x16,
	0x60, 0xc5, 0x99, 0x73, 0xa7, 0xc6, 0xf0, 0x1c, 0x6c, 0x84, 0x8e, 0xd7, 0x47, 0x03, 0x4c, 0x07,
	0xc8, 0xed, 0xc6, 0x94, 0x77, 0xae, 0x2a, 0xc0, 0xa6, 0xe3, 0xf5, 0x8f, 0x30, 0x1d, 0x34, 0xba,
	0x92, 0xe4, 0x68, 0xc9, 0xd4, 0xc3, 0x19, 0x19, 0xfc, 0x12, 0xdc, 0xf6, 0x43, 0xa7, 0xef, 0x78,
	0xd8, 0x45, 0x36, 0x65, 0x13, 0xdc, 0x45, 0xc1, 0xfd, 0xed, 0x64, 0xee, 0x96, 0xb2, 0xa9, 0x51,
	0x36, 0x41, 0xbf, 0xe1, 0xcf, 0x8b, 0xa1, 0x05, 0xee, 0xb8, 0x04, 0x53, 0x16, 0x17, 0x85, 0x09,
	0x17, 0x8f, 0x84, 0x8b, 0xbd, 0x05, 0x11, 0xe1, 0x46, 0xaa, 0x10, 0x4c, 0xf8, 0xd8, 0x74, 0x13,
	0xe4, 0x3c, 0xde, 0x2a, 0x01, 0xbf, 0x64, 0xdf, 0xba, 0x2a, 0xde, 0x55, 0x81, 0x8e, 0xed, 0x79,
	0x07, 0x31, 0x39, 0x86, 0x27, 0x40, 0x67, 0x21, 0xf6, 0x68, 0xe0, 0x87, 0x0c, 0x51, 0xdf, 0xba,
	0x20, 0xcc, 0x30, 0x04, 0x5f, 0x31, 0x61, 0x33, 0x74, 0x62, 0x68, 0x5b, 0x20, 0xcd, 0x3c, 0x9b,
	0x16, 0xc0, 0xef, 0x83, 0x95, 0x21, 0x61, 0xd8, 0xc6, 0x0c, 0x1b, 0x77, 0x05, 0xcd, 0x56, 0x02,
	0xcd, 0x89, 0x82, 0x98, 0x63, 0x30, 0xfc, 0x02, 0xc0, 0x71, 0xae, 0xa2, 0xc4, 0x55, 0x87, 0xa8,
	0x20, 0x0e, 0x79, 0x69, 0xc1, 0xca, 0xe4, 0xdf, 0x38, 0x05, 0xb5, 0x63, 0x2b, 0x73, 0x3d, 0x98,
	0x15, 0xc1, 0x3e, 0xd8, 0x1a, 0xef, 0xfb, 0x89, 0x6e, 0x29, 0xce, 0x8a, 0xf7, 0x93, 0xd2, 0x7e,
	0x5c, 0x0a, 0x5f, 0x16, 0xe6, 0x71, 0xdd, 0x8a, 0x16, 0xa9, 0xe0, 0x19, 0xd8, 0xb5, 0x5c, 0x9f,
	0x92, 0x09, 0x2f, 0x14, 0xf1, 0x72, 0xe9, 0x53, 0x86, 0x54, 0xdb, 0xd1, 0xc3, 0x8e, 0x1b, 0x85,
	0xc4, 0x78, 0xb0, 0xa3, 0xed, 0xae, 0x98, 0xaf, 0x0b, 0xfc, 0x4b, 0x26, 0xda, 0xf2, 0x8e, 0x7c,
	0xca, 0x64, 0xeb, 0x71, 0x28, 0xa1, 0xf0, 0x08, 0x3c, 0xb4, 0x43, 0xec, 0x78, 0x89, 0xb4, 0x21,
	0x19, 0xfa, 0x3c, 0x3d, 0xec, 0x08, 0xbe, 0x6d, 0x01, 0x9c, 0xe3, 0x33, 0x25, 0xa8, 0x10, 0x01,
	0x7d, 0xb6, 0x61, 0x85, 0x1f, 0x01, 0x20, 0x9a, 0x5e, 0xb9, 0x9d, 0x34, 0x11, 0x8c, 0x07, 0x09,
	0xdf, 0x4d, 0xc2, 0xdb, 0xe2, 0xee, 0x65, 0xae, 0xf2, 0x2e, 0x57, 0xda, 0x3f, 0x04, 0x19, 0x4a,
	0xc2, 0x4b, 0xc7, 0x22, 0xb2, 0x39, 0x4f, 0xc9, 0xe6, 0x5c, 0xc9, 0x78, 0x73, 0x5e, 0xb0, 0xc1,
	0xf6, 0x95, 0x85, 0x05, 0xea, 0x60, 0xf9, 0x82, 0x8c, 0x64, 0xff, 0x6f, 0xf2, 0x9f, 0xf0, 0xbb,
	0xe0, 0xc6, 0x25, 0x6f, 0x94, 0x04, 0xdd, 0xda, 0xc1, 0x9d, 0xb9, 0xb4, 0xd7, 0x16, 0x77, 0x13,
	0x53, 0xa2, 0xde, 0x4f, 0xbd, 0xa7, 0x15, 0x7a, 0xa0, 0xf8, 0xea, 0x1a, 0x96, 0xe0, 0x6a, 0x6f,
	0xda, 0xd5, 0xe6, 0x9c, 0xab, 0xb2, 0x37, 0x9a, 0xf4, 0xf3, 0xab, 0x34, 0xc8, 0x4d, 0x27, 0x32,
	0x18, 0x80, 0x7c, 0x0f, 0xbb, 0x6e, 0x17, 0x5b, 0x17, 0x71, 0xa3, 0xac, 0x89, 0xdd, 0xfb, 0x83,
	0xeb, 0xe4, 0xc1, 0xf1, 0xf0, 0x50, 0x71, 0x24, 0x74, 0xd1, 0xb9, 0xde, 0x94, 0x0e, 0x7e, 0x04,
	0x72, 0x36, 0xe9, 0xe1, 0x88, 0xdf, 0x8b, 0x84, 0xed, 0xab, 0x02, 0x95, 0x55, 0x70, 0xe9, 0x09,
	0x7e, 0x09, 0x74, 0x95, 0xb7, 0xe5, 0x81, 0xf3, 0x43, 0x6a, 0x2c, 0x8b, 0xd2, 0xf7, 0xce, 0x37,
	0x9a, 0x72, 0x5b, 0x59, 0x9b, 0x79, 0x3a, 0x35, 0xa6, 0xf0, 0x00, 0xdc, 0x72, 0x7d, 0x0b, 0xbb,
	0x0e, 0x1b, 0xa1, 0x67, 0xc4, 0xe9, 0x0f, 0x18, 0xc2, 0xcf, 0x70, 0x48, 0xc4, 0xe5, 0x67, 0xc5,
	0xdc, 0x88, 0x95, 0xe7, 0x42, 0x57, 0xe6, 0x2a, 0x6e, 0x43, 0x2d, 0xec, 0x12, 0x34, 0x63, 0x29,
	0xae, 0x31, 0x2b, 0xe6, 0x86, 0x50, 0x36, 0xa6, 0x0c, 0x0b, 0x6f, 0x02, 0x7d, 0x76, 0x32, 0x10,
	0x82, 0xf4, 0x05, 0x19, 0x51, 0x43, 0xdb, 0x59, 0xde, 0x5d, 0x35, 0xc5, 0xef, 0x62, 0x0b, 0xdc,
	0x4e, 0x8e, 0x33, 0xcc, 0x83, 0xb5, 0x66, 0x0b, 0x1d, 0x96, 0x1b, 0x8d, 0x4a, 0xb9, 0xfa, 0x89,
	0xbe, 0x04, 0x75, 0x90, 0x29, 0x37, 0x3f, 0x43, 0xf5, 0x66, 0xed, 0xb4, 0x75, 0xdc, 0xec, 0xe8,
	0x1a, 0x84, 0x20, 0x57, 0xab, 0x1f, 0x96, 0xcf, 0x1a, 0x1d, 0xd4, 0x3e, 0xab, 0xb4, 0xeb, 0x1d,
	0x3d, 0x55, 0xe8, 0x82, 0xcd, 0xa4, 0xec, 0x0d, 0x3f, 0x06, 0x19, 0x6b, 0xe0, 0xf3, 0xf3, 0x60,
	0xf9, 0x91, 0xc7, 0xd4, 0x91, 0xba, 0xf2, 0x3a, 0xa0, 0xee, 0xbc, 0x7b, 0xa9, 0xdd, 0x94, 0xb9,
	0x26, 0x8d, 0xab, 0xdc, 0xb6, 0xf0, 0xcb, 0x34, 0xd0, 0x67, 0x2b, 0x1c, 0x7c, 0x0a, 0xd6, 0x87,
	0x8e, 0xe7, 0x0c, 0xa3, 0x21, 0x12, 0xe5, 0x92, 0x3a, 0x2f, 0xc8, 0x95, 0x5e, 0xde, 0x7d, 0x5b,
	0x7a, 0xc9, 0x70, 0x2f, 0x37, 0x0f, 0x6e, 0x18, 0x5f, 0x7d, 0xf5, 0x55, 0xda, 0xcc, 0x2b, 0x12,
	0xce, 0xdf, 0x76, 0x5e, 0x10, 0xf8, 0x13, 0x90, 0xb5, 0x49, 0x10, 0x12, 0x0b, 0x33, 0x62, 0xa3,
	0xcb, 0xb7, 0xd4, 0x96, 0x7a, 0x7c, 0xbd, 0xc2, 0x5b, 0xaa, 0x8d, 0x6d, 0x9f, 0xbe, 0x25, 0xba,
	0xd5, 0x8c, 0x3d, 0x21, 0x81, 0x36, 0xc8, 0x8a, 0xba, 0xde, 0x8b, 0x3c, 0x99, 0xdf, 0x97, 0xc5,
	0x09, 0xb9, 0x2e, 0x3b, 0x1f, 0x1c, 0x2a, 0xd3, 0xa9, 0x93, 0x91, 0x19, 0x4c, 0x68, 0x44, 0x6c,
	0xf0, 0xf3, 0x99, 0xd8, 0xa4, 0xff, 0x87, 0xd8, 0x48, 0x92, 0x38, 0x36, 0x85, 0x06, 0xc8, 0x4c,
	0xae, 0x0f, 0x7e, 0x00, 0x32, 0x11, 0x25, 0x88, 0x32, 0x5b, 0x74, 0x2b, 0x2a, 0xfc, 0x85, 0x39,
	0x17, 0x15, 0xdf, 0x77, 0xe5, 0x8d, 0x0f, 0x44, 0x94, 0xb4, 0x99, 0xcd, 0xd7, 0x51, 0x2c, 0x81,
	0xcc, 0xe4, 0x7a, 0xe0, 0x1a, 0xb8, 0xf9, 0xe9, 0xa7, 0xe8, 0xa8, 0xdc, 0x3e, 0xd2, 0x97, 0xe0,
	0x3a, 0xc8, 0x9e, 0x9c, 0x99, 0x27, 0x67, 0xa6, 0x10, 0xa0, 0x03, 0x5d, 0x2b, 0x7c, 0x08, 0x36,
	0x12, 0x7a, 0x11, 0xf8, 0x26, 0xc8, 0xf3, 0x49, 0x88, 0xbb, 0xd2, 0x80, 0x60, 0x9b, 0x84, 0x62,
	0x1e, 0x2b, 0x66, 0x36, 0xa2, 0x84, 0xdf, 0x59, 0x8e, 0x84, 0xb0, 0xf0, 0xef, 0x34, 0xc8, 0x4d,
	0xb7, 0x02, 0xf0, 0x13, 0x70, 0x47, 0x16, 0xa4, 0x11, 0x0a, 0xb0, 0xe7, 0x58, 0x88, 0x0d, 0x78,
	0xcb, 0xed, 0xbb, 0xb6, 0x5a, 0xca, 0x86, 0xfa, 0x2e, 0xbc, 0xe5, 0x2f, 0x9d, 0xca, 0x07, 0x28,
	0xf3, 0x96, 0xb2, 0x39, 0xe5, 0x26, 0x9d, 0xd8, 0x02, 0x3a, 0x60, 0xf3, 0x85, 0xef, 0x11, 0x79,
	0xbe, 0x27, 0x7a, 0x13, 0xb9, 0x7f, 0xde, 0xbd, 0x4e, 0x6f, 0x52, 0xfa, 0xb1, 0xef, 0x11, 0x91,
	0x04, 0x26, 0xba, 0xa0, 0xf5, 0x17, 0xb3, 0x42, 0xf8, 0x73, 0xb0, 0x35, 0x93, 0x1b, 0x88, 0x3d,
	0xe1, 0x51, 0xbe, 0xd5, 0x7c, 0x78, 0x2d, 0x8f, 0xd3, 0x79, 0x84, 0xd8, 0x13, 0x8e, 0x0d, 0x77,
	0x81, 0x0e, 0x1e, 0x83, 0x8d, 0x28, 0xb0, 0x31, 0x23, 0x68, 0x48, 0xc2, 0x3e, 0x41, 0xcf, 0x1c,
	0xcf, 0xf6, 0x9f, 0xbd, 0xf2, 0x41, 0xc7, 0x5c, 0x97, 0x56, 0x27, 0xdc, 0xe8, 0x5c, 0xd8, 0x14,
	0x7e, 0xa7, 0x81, 0xf5, 0xb9, 0x55, 0xc3, 0x0f, 0x40, 0x3e, 0xf4, 0x23, 0xc6, 0xf7, 0x2e, 0xf1,
	0x70, 0xd7, 0x25, 0x57, 0x7e, 0x90, 0x9c, 0xc2, 0xd6, 0x25, 0x14, 0x1e, 0x02, 0x7d, 0xc8, 0x1b,
	0x05, 0xf5, 0x82, 0x25, 0x76, 0x7f, 0xea, 0xd5, 0xbb, 0xdf, 0xcc, 0x0d, 0x1d, 0x4f, 0x85, 0x49,
	0x6c, 0xf7, 0x02, 0x30, 0x16, 0x85, 0xa7, 0xb2, 0x05, 0xee, 0x8e, 0x3f, 0x41, 0xfc, 0x22, 0x1b,
	0x10, 0xcb, 0xe9, 0x39, 0x24, 0x2c, 0x9e, 0x83, 0xec, 0xd4, 0x2b, 0x1b, 0x04, 0xe0, 0xb5, 0x76,
	0xa7, 0xdc, 0x39, 0xae, 0xea, 0x4b, 0x30, 0x07, 0x40, 0xbb, 0x63, 0x1e, 0x57, 0x3b, 0xa8, 0xd6,
	0x6c, 0xeb, 0x1a, 0x4f, 0xbc, 0x8d, 0xd6, 0x93, 0xe3, 0x6a, 0xb9, 0x21, 0x04, 0x29, 0x78, 0x13,
	0x2c, 0xd7, 0x6b, 0x6d, 0x7d, 0x99, 0x67, 0xe0, 0x96, 0x79, 0xfc, 0xe4, 0xb8, 0xc9, 0x55, 0xed,
	0x8e, 0x9e, 0x2e, 0xfe, 0x14, 0xac, 0xc4, 0xcf, 0x4b, 0xdc, 0xce, 0x6c, 0x9d, 0x35, 0x6b, 0xc8,
	0x6c, 0x55, 0x8e, 0x9b, 0xf2, 0xc8, 0x34, 0xea, 0xe5, 0x76, 0x07, 0x99, 0xf5, 0x1f, 0x9d, 0xd5,
	0xdb, 0x3c, 0x63, 0x67, 0xc1, 0xaa, 0x79, 0xdc, 0x7c, 0x22, 0x0f, 0x55, 0x8a, 0x4f, 0xc3, 0x2c,
	0x37, 0x6b, 0xad, 0x13, 0x7d, 0x19, 0x6e, 0x80, 0xfc, 0x24, 0x39, 0x6a, 0x54, 0xf4, 0x34, 0x07,
	0x9c, 0x94, 0x9f, 0x34, 0xea, 0x4f, 0xf5, 0x1b, 0xc5, 0x77, 0x40, 0x7e, 0xe6, 0x12, 0x09, 0x57,
	0x40, 0xba, 0x7c, 0xd6, 0x69, 0xe9, 0x4b, 0xfc, 0xac, 0x3e, 0x7d, 0x1b, 0xb5, 0x9a, 0x8d, 0xcf,
	0x74, 0x4d, 0x0c, 0xde, 0x95, 0x83, 0x54, 0xb1, 0x03, 0x8c, 0x45, 0x6d, 0x29, 0xdc, 0x02, 0x77,
	0xce, 0xda, 0x75, 0x54, 0x6d, 0x35, 0x0f, 0x8f, 0x9f, 0x9c, 0x99, 0xf5, 0x1a, 0x3a, 0x35, 0x5b,
	0x9d, 0x56, 0xb5, 0xd5, 0xd0, 0x97, 0x62, 0x65, 0xad, 0x75, 0xde, 0x6c, 0x77, 0xcc, 0x7a, 0xf9,
	0xe4, 0xa5, 0x52, 0xab, 0xac, 0x89, 0xe7, 0x37, 0x19, 0xe8, 0x8f, 0xd3, 0x2b, 0x19, 0x3d, 0xfb,
	0x71, 0x7a, 0x25, 0xaf, 0xeb, 0xc5, 0x73, 0x00, 0xcf, 0xe6, 0xef, 0x64, 0x65, 0x90, 0x93, 0xef,
	0xe3, 0x48, 0x3d, 0xc5, 0x8f, 0x53, 0xd3, 0xe2, 0x1b, 0x6d, 0x56, 0x5a, 0xa8, 0x61, 0x11, 0x83,
	0xbb, 0x0b, 0xdb, 0x5f, 0x58, 0x03, 0x59, 0x66, 0x05, 0xe8, 0x82, 0x90, 0x00, 0xbb, 0xce, 0x25,
	0xb9, 0xa2, 0x63, 0xec, 0x58, 0xc1, 0x27, 0x31, 0xcc, 0xcc, 0xb0, 0x89, 0xd1, 0xc1, 0xdf, 0x52,
	0xe0, 0x8e, 0x8a, 0xd5, 0x78, 0xbb, 0xb4, 0x65, 0xc7, 0x08, 0xcf, 0x41, 0xae, 0x2d, 0x9d, 0x4b,
	0x00, 0x85, 0x33, 0xaf, 0x73, 0x63, 0x0b, 0x55, 0x79, 0x0b, 0x0f, 0x16, 0xea, 0x69, 0xe0, 0x7b,
	0x94, 0x14, 0x97, 0x76, 0xb5, 0xef, 0x69, 0x30, 0x04, 0x1b, 0xc7, 0x9e, 0x15, 0x92, 0x21, 0xf1,
	0x18, 0x76, 0xc7, 0xec, 0x33, 0x97, 0xbf, 0x09, 0xc8, 0x9c, 0xa3, 0xbd, 0xeb, 0x40, 0xa7, 0x7c,
	0x52, 0x90, 0x3d, 0x24, 0xcc, 0x1a, 0xfc, 0xff, 0xd6, 0xf2, 0xf0, 0xeb, 0xbf, 0xfe, 0xeb, 0x37,
	0xa9, 0xad, 0xe2, 0xed, 0xa9, 0xff, 0x77, 0xbc, 0xaf, 0x8e, 0x3c, 0x7d, 0x5f, 0xdb, 0xab, 0xec,
	0xff, 0xfe, 0x9f, 0xf7, 0x35, 0x50, 0x70, 0x7c, 0xc9, 0x15, 0x84, 0xfe, 0xf3, 0xd1, 0x14, 0x6d,
	0x65, 0xa5, 0x6a, 0x53, 0xb1, 0x49, 0x4f, 0xb5, 0x5f, 0x6b, 0x5a, 0xf7, 0x35, 0x91, 0x14, 0x1e,
	0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x9a, 0xc5, 0x05, 0xea, 0x19, 0x00, 0x00,
}
