// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eds.proto

package discoveryservice

import (
	_ "envoy/api/v2"
	endpoint "envoy/api/v2/endpoint"
	_type "envoy/type"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Each route from RDS will map to a single cluster or traffic split across
// clusters using weights expressed in the RDS WeightedCluster.
//
// With EDS, each cluster is treated independently from a LB perspective, with
// LB taking place between the Localities within a cluster and at a finer
// granularity between the hosts within a locality. For a given cluster, the
// effective weight of a host is its load_balancing_weight multiplied by the
// load_balancing_weight of its Locality.
type ClusterLoadAssignment struct {
	// Name of the cluster. This will be the :ref:`service_name
	// <envoy_api_field_Cluster.EdsClusterConfig.service_name>` value if specified
	// in the cluster :ref:`EdsClusterConfig
	// <envoy_api_msg_Cluster.EdsClusterConfig>`.
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// List of endpoints to load balance to.
	Endpoints []*endpoint.LocalityLbEndpoints `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Map of named endpoints that can be referenced in LocalityLbEndpoints.
	NamedEndpoints map[string]*endpoint.Endpoint `protobuf:"bytes,5,rep,name=named_endpoints,json=namedEndpoints,proto3" json:"named_endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Load balancing policy settings.
	Policy               *ClusterLoadAssignment_Policy `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClusterLoadAssignment) Reset()         { *m = ClusterLoadAssignment{} }
func (m *ClusterLoadAssignment) String() string { return proto.CompactTextString(m) }
func (*ClusterLoadAssignment) ProtoMessage()    {}
func (*ClusterLoadAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffc471a713d6410f, []int{0}
}

func (m *ClusterLoadAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterLoadAssignment.Unmarshal(m, b)
}
func (m *ClusterLoadAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterLoadAssignment.Marshal(b, m, deterministic)
}
func (m *ClusterLoadAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterLoadAssignment.Merge(m, src)
}
func (m *ClusterLoadAssignment) XXX_Size() int {
	return xxx_messageInfo_ClusterLoadAssignment.Size(m)
}
func (m *ClusterLoadAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterLoadAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterLoadAssignment proto.InternalMessageInfo

func (m *ClusterLoadAssignment) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterLoadAssignment) GetEndpoints() []*endpoint.LocalityLbEndpoints {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *ClusterLoadAssignment) GetNamedEndpoints() map[string]*endpoint.Endpoint {
	if m != nil {
		return m.NamedEndpoints
	}
	return nil
}

func (m *ClusterLoadAssignment) GetPolicy() *ClusterLoadAssignment_Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

// Load balancing policy settings.
type ClusterLoadAssignment_Policy struct {
	// Action to trim the overall incoming traffic to protect the upstream
	// hosts. This action allows protection in case the hosts are unable to
	// recover from an outage, or unable to autoscale or unable to handle
	// incoming traffic volume for any reason.
	//
	// At the client each category is applied one after the other to generate
	// the 'actual' drop percentage on all outgoing traffic. For example:
	//
	// .. code-block:: json
	//
	//  { "drop_overloads": [
	//      { "category": "throttle", "drop_percentage": 60 }
	//      { "category": "lb", "drop_percentage": 50 }
	//  ]}
	//
	// The actual drop percentages applied to the traffic at the clients will be
	//    "throttle"_drop = 60%
	//    "lb"_drop = 20%  // 50% of the remaining 'actual' load, which is 40%.
	//    actual_outgoing_load = 20% // remaining after applying all categories.
	DropOverloads []*ClusterLoadAssignment_Policy_DropOverload `protobuf:"bytes,2,rep,name=drop_overloads,json=dropOverloads,proto3" json:"drop_overloads,omitempty"`
	// Priority levels and localities are considered overprovisioned with this
	// factor (in percentage). This means that we don't consider a priority
	// level or locality unhealthy until the percentage of healthy hosts
	// multiplied by the overprovisioning factor drops below 100.
	// With the default value 140(1.4), Envoy doesn't consider a priority level
	// or a locality unhealthy until their percentage of healthy hosts drops
	// below 72%. For example:
	//
	// .. code-block:: json
	//
	//  { "overprovisioning_factor": 100 }
	//
	// Read more at :ref:`priority levels <arch_overview_load_balancing_priority_levels>` and
	// :ref:`localities <arch_overview_load_balancing_locality_weighted_lb>`.
	OverprovisioningFactor *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=overprovisioning_factor,json=overprovisioningFactor,proto3" json:"overprovisioning_factor,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *ClusterLoadAssignment_Policy) Reset()         { *m = ClusterLoadAssignment_Policy{} }
func (m *ClusterLoadAssignment_Policy) String() string { return proto.CompactTextString(m) }
func (*ClusterLoadAssignment_Policy) ProtoMessage()    {}
func (*ClusterLoadAssignment_Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffc471a713d6410f, []int{0, 1}
}

func (m *ClusterLoadAssignment_Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterLoadAssignment_Policy.Unmarshal(m, b)
}
func (m *ClusterLoadAssignment_Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterLoadAssignment_Policy.Marshal(b, m, deterministic)
}
func (m *ClusterLoadAssignment_Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterLoadAssignment_Policy.Merge(m, src)
}
func (m *ClusterLoadAssignment_Policy) XXX_Size() int {
	return xxx_messageInfo_ClusterLoadAssignment_Policy.Size(m)
}
func (m *ClusterLoadAssignment_Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterLoadAssignment_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterLoadAssignment_Policy proto.InternalMessageInfo

func (m *ClusterLoadAssignment_Policy) GetDropOverloads() []*ClusterLoadAssignment_Policy_DropOverload {
	if m != nil {
		return m.DropOverloads
	}
	return nil
}

func (m *ClusterLoadAssignment_Policy) GetOverprovisioningFactor() *wrappers.UInt32Value {
	if m != nil {
		return m.OverprovisioningFactor
	}
	return nil
}

type ClusterLoadAssignment_Policy_DropOverload struct {
	// Identifier for the policy specifying the drop.
	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// Percentage of traffic that should be dropped for the category.
	DropPercentage       *_type.FractionalPercent `protobuf:"bytes,2,opt,name=drop_percentage,json=dropPercentage,proto3" json:"drop_percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ClusterLoadAssignment_Policy_DropOverload) Reset() {
	*m = ClusterLoadAssignment_Policy_DropOverload{}
}
func (m *ClusterLoadAssignment_Policy_DropOverload) String() string { return proto.CompactTextString(m) }
func (*ClusterLoadAssignment_Policy_DropOverload) ProtoMessage()    {}
func (*ClusterLoadAssignment_Policy_DropOverload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffc471a713d6410f, []int{0, 1, 0}
}

func (m *ClusterLoadAssignment_Policy_DropOverload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload.Unmarshal(m, b)
}
func (m *ClusterLoadAssignment_Policy_DropOverload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload.Marshal(b, m, deterministic)
}
func (m *ClusterLoadAssignment_Policy_DropOverload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload.Merge(m, src)
}
func (m *ClusterLoadAssignment_Policy_DropOverload) XXX_Size() int {
	return xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload.Size(m)
}
func (m *ClusterLoadAssignment_Policy_DropOverload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterLoadAssignment_Policy_DropOverload proto.InternalMessageInfo

func (m *ClusterLoadAssignment_Policy_DropOverload) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ClusterLoadAssignment_Policy_DropOverload) GetDropPercentage() *_type.FractionalPercent {
	if m != nil {
		return m.DropPercentage
	}
	return nil
}

func init() {
	proto.RegisterType((*ClusterLoadAssignment)(nil), "envoy.api.v2.ClusterLoadAssignment")
	proto.RegisterMapType((map[string]*endpoint.Endpoint)(nil), "envoy.api.v2.ClusterLoadAssignment.NamedEndpointsEntry")
	proto.RegisterType((*ClusterLoadAssignment_Policy)(nil), "envoy.api.v2.ClusterLoadAssignment.Policy")
	proto.RegisterType((*ClusterLoadAssignment_Policy_DropOverload)(nil), "envoy.api.v2.ClusterLoadAssignment.Policy.DropOverload")
}

func init() { proto.RegisterFile("eds.proto", fileDescriptor_ffc471a713d6410f) }

var fileDescriptor_ffc471a713d6410f = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xb1, 0x6e, 0xd4, 0x4c,
	0x10, 0xc7, 0xb3, 0xbe, 0x4b, 0x94, 0xdb, 0xe4, 0x4b, 0x22, 0x7f, 0x40, 0x2c, 0xeb, 0x48, 0x4e,
	0x27, 0x90, 0xa2, 0x08, 0xd9, 0xe8, 0x22, 0x14, 0x94, 0x8e, 0x23, 0x39, 0x09, 0x14, 0x85, 0x93,
	0x23, 0x10, 0x15, 0xc7, 0x9e, 0xbd, 0x31, 0x2b, 0x7c, 0x3b, 0xcb, 0x7a, 0xcf, 0xe0, 0x82, 0x86,
	0x8a, 0x9e, 0x97, 0xe0, 0x19, 0xa8, 0x28, 0xe9, 0x28, 0xe8, 0x29, 0x10, 0x0d, 0xa2, 0xe2, 0x0d,
	0x90, 0xed, 0xb5, 0x13, 0x93, 0x8b, 0x44, 0x41, 0x37, 0xeb, 0x99, 0xf9, 0xed, 0xcc, 0x7f, 0x67,
	0x8c, 0x5b, 0x34, 0x88, 0x1d, 0x21, 0x41, 0x81, 0xb9, 0x4c, 0x79, 0x02, 0xa9, 0x43, 0x04, 0x73,
	0x92, 0x9e, 0xdd, 0xce, 0x4f, 0x2e, 0x11, 0xcc, 0x4d, 0x7a, 0x6e, 0xc0, 0x62, 0x1f, 0x12, 0x2a,
	0xd3, 0x22, 0xd6, 0xbe, 0x56, 0xf3, 0x52, 0x1e, 0x08, 0x60, 0x5c, 0x55, 0x86, 0x8e, 0xb2, 0x8a,
	0x28, 0x95, 0x0a, 0xea, 0x0a, 0x2a, 0x7d, 0x5a, 0x79, 0xda, 0x21, 0x40, 0x18, 0xd1, 0x1c, 0x40,
	0x38, 0x07, 0x45, 0x14, 0x03, 0xae, 0x2b, 0xb1, 0xd7, 0x13, 0x12, 0xb1, 0x80, 0x28, 0xea, 0x96,
	0x86, 0x76, 0x5c, 0x0a, 0x21, 0x84, 0xdc, 0x74, 0x33, 0x4b, 0x7f, 0xdd, 0xd0, 0xb0, 0xfc, 0x34,
	0x9e, 0x9e, 0xb8, 0x2f, 0x25, 0x11, 0x82, 0x4a, 0x8d, 0xeb, 0xfe, 0x9a, 0xc7, 0x97, 0xef, 0x46,
	0xd3, 0x58, 0x51, 0x79, 0x08, 0x24, 0xb8, 0x13, 0xc7, 0x2c, 0xe4, 0x13, 0xca, 0x95, 0x79, 0x03,
	0x2f, 0xfb, 0x85, 0x63, 0xc4, 0xc9, 0x84, 0x5a, 0xa8, 0x83, 0xb6, 0x5a, 0xfd, 0xd6, 0x87, 0x1f,
	0x1f, 0x1b, 0x4d, 0x69, 0x74, 0x90, 0xb7, 0xa4, 0xdd, 0x47, 0x64, 0x42, 0xcd, 0x23, 0xdc, 0x2a,
	0x1b, 0x8c, 0x2d, 0xa3, 0xd3, 0xd8, 0x5a, 0xea, 0x6d, 0x3b, 0x67, 0x45, 0x73, 0xaa, 0xfe, 0x0f,
	0xc1, 0x27, 0x11, 0x53, 0xe9, 0xe1, 0xf8, 0xa0, 0xcc, 0xe8, 0x37, 0x3f, 0x7d, 0xdd, 0x9c, 0xf3,
	0x4e, 0x11, 0xe6, 0x53, 0xbc, 0x9a, 0xdd, 0x1a, 0x8c, 0x4e, 0xa9, 0xf3, 0x39, 0x75, 0xb7, 0x4e,
	0x9d, 0x59, 0xbb, 0x93, 0x95, 0x14, 0x54, 0xf4, 0x03, 0xae, 0x64, 0xea, 0xad, 0xf0, 0xda, 0x47,
	0xb3, 0x8f, 0x17, 0x04, 0x44, 0xcc, 0x4f, 0xad, 0x66, 0x07, 0x9d, 0x2f, 0x77, 0x36, 0x78, 0x98,
	0x67, 0x78, 0x3a, 0xd3, 0x1e, 0xe3, 0xff, 0x67, 0x5c, 0x65, 0xae, 0xe1, 0xc6, 0x73, 0x9a, 0x16,
	0x8a, 0x79, 0x99, 0x69, 0xde, 0xc2, 0xf3, 0x09, 0x89, 0xa6, 0xd4, 0x32, 0xf2, 0xbb, 0x36, 0x2f,
	0x90, 0xa6, 0xe4, 0x78, 0x45, 0xf4, 0x9e, 0x71, 0x1b, 0xd9, 0x9f, 0x0d, 0xbc, 0x50, 0x5c, 0x6b,
	0x3e, 0xc1, 0x2b, 0x81, 0x04, 0x31, 0xca, 0xa6, 0x2d, 0x02, 0x12, 0x94, 0x4a, 0xef, 0xfe, 0x7d,
	0xe9, 0xce, 0xbe, 0x04, 0xf1, 0x40, 0xe7, 0x7b, 0xff, 0x05, 0x67, 0x4e, 0x99, 0xe8, 0xeb, 0x19,
	0x5a, 0x48, 0x48, 0x58, 0xcc, 0x80, 0x33, 0x1e, 0x8e, 0x4e, 0x88, 0xaf, 0x40, 0x5a, 0x8d, 0xbc,
	0xee, 0xb6, 0x53, 0x8c, 0x93, 0x53, 0x8e, 0x93, 0xf3, 0xf0, 0x1e, 0x57, 0x3b, 0xbd, 0x47, 0x59,
	0xb5, 0x7a, 0x36, 0xb6, 0x8d, 0xce, 0x9c, 0x77, 0xe5, 0x4f, 0xce, 0x20, 0xc7, 0xd8, 0xaf, 0xf1,
	0xf2, 0xd9, 0x02, 0xcc, 0xeb, 0x78, 0xd1, 0x27, 0x8a, 0x86, 0x20, 0xd3, 0xf3, 0x03, 0x56, 0xb9,
	0xcc, 0x01, 0x5e, 0xcd, 0x1b, 0xd7, 0x8b, 0x42, 0xc2, 0x52, 0xc8, 0xab, 0xba, 0xf3, 0x6c, 0x8d,
	0x9c, 0x81, 0x24, 0x7e, 0xb6, 0x2a, 0x24, 0x1a, 0x16, 0x71, 0x5e, 0x2e, 0xd7, 0xb0, 0x4a, 0xba,
	0xdf, 0x5c, 0x44, 0x6b, 0x46, 0xef, 0x27, 0xc2, 0x56, 0xa9, 0xf4, 0x7e, 0xb9, 0xbc, 0xc7, 0x54,
	0x26, 0xcc, 0xa7, 0xe6, 0x63, 0xbc, 0x7a, 0xac, 0x24, 0x25, 0x93, 0xd3, 0x49, 0xd9, 0xa8, 0xcb,
	0x5b, 0xa5, 0x78, 0xf4, 0xc5, 0x94, 0xc6, 0xca, 0xde, 0xbc, 0xd0, 0x1f, 0x0b, 0xe0, 0x31, 0xed,
	0xce, 0x6d, 0xa1, 0x9b, 0xc8, 0x9c, 0xe2, 0x95, 0x01, 0x55, 0xfe, 0xb3, 0x7f, 0x08, 0xee, 0xbe,
	0xf9, 0xf2, 0xfd, 0x9d, 0xd1, 0xee, 0xae, 0xd7, 0xfe, 0x43, 0x7b, 0xd5, 0xce, 0xec, 0xa1, 0xed,
	0xbe, 0xfb, 0xfe, 0xdb, 0x06, 0xc2, 0x36, 0x83, 0x02, 0x26, 0x24, 0xbc, 0x4a, 0x6b, 0xdc, 0xfe,
	0xe2, 0x41, 0x10, 0x0f, 0xb3, 0x07, 0x1d, 0xa2, 0xb7, 0x08, 0x8d, 0x17, 0xf2, 0xc7, 0xdd, 0xf9,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x19, 0x8c, 0xe3, 0xff, 0x04, 0x00, 0x00,
}
